<!--<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <div class="orders-container">
                                <div class="orders-header">
                                    <h6>Latest Orders</h6>
                                </div>
                                <ul class="orders-list">
                                    <li class="order-item">
                                        <div class="row">
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker">Ned Stards</div>
                                                <div class="item-time">
                                                    <i class="fa fa-calendar"></i>
                                                    <span>10 minutes ago</span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <span class="currency">$</span>
                                                    <span class="price">400</span>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="item-more" href="">
                                            <i></i>
                                        </a>
                                    </li>
                                    <li class="order-item top">
                                        <div class="row">
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker">Steve Lewis</div>
                                                <div class="item-time">
                                                    <i class="fa fa-calendar"></i>
                                                    <span>2 hours ago</span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <span class="currency">$</span>
                                                    <span class="price">620</span>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="item-more" href="">
                                            <i></i>
                                        </a>
                                    </li>
                                    <li class="order-item">
                                        <div class="row">
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker">John Ford</div>
                                                <div class="item-time">
                                                    <i class="fa fa-calendar"></i>
                                                    <span>Today 8th July</span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <span class="currency">$</span>
                                                    <span class="price">220</span>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="item-more" href="">
                                            <i></i>
                                        </a>
                                    </li>
                                    <li class="order-item">
                                        <div class="row">
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker">Kim Basinger</div>
                                                <div class="item-time">
                                                    <i class="fa fa-calendar"></i>
                                                    <span>Yesterday 7th July</span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <span class="currency">$</span>
                                                    <span class="price">400</span>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="item-more" href="">
                                            <i></i>
                                        </a>
                                    </li>
                                    <li class="order-item">
                                        <div class="row">
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker">Steve Lewis</div>
                                                <div class="item-time">
                                                    <i class="fa fa-calendar"></i>
                                                    <span>5th July</span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <span class="currency">$</span>
                                                    <span class="price">340</span>
                                                </div>
                                            </div>
                                        </div>
                                        <a class="item-more" href="">
                                            <i></i>
                                        </a>
                                    </li>
                                </ul>
                                <div class="orders-footer">
                                    <a class="show-all" href=""><i class="fa fa-angle-down"></i> Show All</a>
                                    <div class="help">
                                        <a href=""><i class="fa fa-question"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>


<div class="col-lg-4 col-sm-12 col-xs-12">
                            <div class="widget">
                                <div class="widget-header bordered-bottom bordered-themeprimary">
                                    <i class="widget-icon fa fa-tasks themeprimary"></i>
                                    <span class="widget-caption themeprimary">Task Board</span>
                                </div>
                                <div class="widget-body no-padding">
                                    <div class="task-container">
                                        <div class="task-search">
                                            <span class="input-icon">
                                                <input type="text" class="form-control" placeholder="Search Tasks">
                                                <i class="fa fa-search gray"></i>
                                            </span>
                                        </div>
                                        <ul class="tasks-list">
                                            <li class="task-item">
                                                <div class="task-check">
                                                    <label>
                                                        <input type="checkbox">
                                                        <span class="text"></span>
                                                    </label>
                                                </div>
                                                <div class="task-state">
                                                    <span class="label label-yellow">
                                                        In Progress
                                                    </span>
                                                </div>
                                                <div class="task-time">1 hour ago</div>
                                                <div class="task-body">Ask to the sysadmins to install Python 3 on the server and run it</div>
                                                <div class="task-creator"><a href="">Cameron Hetfield</a></div>
                                                <div class="task-assignedto">assigned to you</div>
                                            </li>
                                            <li class="task-item">
                                                <div class="task-check">
                                                    <label>
                                                        <input type="checkbox">
                                                        <span class="text"></span>
                                                    </label>
                                                </div>
                                                <div class="task-state">
                                                    <span class="label label-orange">
                                                        Active
                                                    </span>
                                                </div>
                                                <div class="task-time">2 hours ago</div>
                                                <div class="task-body">Write documentation for the new API with test and deploy specifications</div>
                                                <div class="task-creator"><a href="">Behrang Nitsche</a></div>
                                                <div class="task-assignedto">assigned to you</div>
                                            </li>
                                            <li class="task-item">
                                                <div class="task-check">
                                                    <label>
                                                        <input type="checkbox">
                                                        <span class="text"></span>
                                                    </label>
                                                </div>
                                                <div class="task-state">
                                                    <span class="label label-palegreen">
                                                        Approved
                                                    </span>
                                                </div>
                                                <div class="task-time">yesterday</div>
                                                <div class="task-body">Code refactoring and rewriting silly codes and test it</div>
                                                <div class="task-creator"><a href="">David Fincher</a></div>
                                                <div class="task-assignedto">assigned to Kim</div>
                                            </li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        </div>

-->