<?php

include APPLICATION_PATH.'/forms/slide/adicionar.php';
include APPLICATION_PATH.'/decorators/Form.php';


$decform = new Decorators_Form();
$form = new Forms_Slide_Adicionar(array('titulo' => 'Novo slide', 'cursos' => $this->crusos));
$form->addDecorator($decform);
echo $form;

?>


<div class="col-lg-6 col-sm-6 col-xs-12">
    <div class="widget">
        <div class="widget-header bordered-bottom bordered-blue">
            <span class="widget-caption">Preview</span>
        </div>
        <div class="widget-body" id="preview_visor">

        </div>
    </div>        
</div>

<script type="text/javascript">
$(function() {

    $('#Preview').bind('click', function() {
        var html = $('#ST_SLIDE_SLI').val();
        $('#preview_visor').html(html);
    });
})


</script>