<?php

    include_once 'menueditcurso.php';
?>
    
<div id="divModal"></div>
<?php

include_once '/decorators/form.php';
include_once '/forms/curso/editarslides.php';
include_once '/forms/curso/deleteslide.php';
include_once '/forms/curso/comp.php';

$curso = $this->curso;
?>

<div id="arquivo" style="display:none"><?php echo $curso[0]['ST_IDENT_CR']; ?></div>
<div id="curso" style="display:none"><?php echo $curso[0]['ID_ID_CR']; ?></div>

<div id="divPrincipal">
    <?php
        $decform = new Decorators_Form();
        $form = new Forms_Curso_EditarSlides(array('titulo' => 'Editar curso: '.$curso[0]['ST_NOME_CR'], 'icone' => 'glyphicon glyphicon-edit'));
        $form->addDecorator($decform);
        $form->populate($curso[0]);
        echo $form;
    ?>
</div>
<div id="divSecundario"></div>
<div id="divFormExcluir" style="display:none;">
    <?php
        $formExcluir = new Forms_Curso_DeleteSlide();
        $formExcluir->addDecorator($decform);
        $formExcluir->populate($curso[0]);
        echo $formExcluir;   
    ?>
</div>

<div id="infoCompl" style="display:none;">
    <?php
        $formComp = new Forms_Curso_Comp(array('titulo' => utf8_encode('Mais informações'), 'icone' => 'glyphicon glyphicon-info-sign'));
        $formComp->addDecorator($decform);
        $formComp->populate($curso[0]);
        echo $formComp;      
    ?> 
</div>

<div id="infoVentas" style="display:none;">
    
</div>

<script type="text/javascript">
    
    function fecharModal() {
        $('.btnCancelar').bind('click', function() {
            $('#divModal').dialog('destroy');
        });
    }
    
    function excluirCurso() {
        $('#btnExcluir').bind('click', function() {
           $('#formExcluir').submit(); 
        });
    }
    
    $(function() {
        
        $('#btnAtualizarComp').bind('click', function() {
            var des = $('#ST_DESCR_CR').val();
            var obj = $('#ST_OBJETIVO_CR').val();
            var cont = $('#ST_CONTEUDO_CR').val();
            var car = $('#ST_CARACT_CR').val();
            var curso = $('#curso').html();
            $.post("atualizarslidecomp", {curso: curso , ST_CONTEUDO_CR: cont, ST_DESCR_CR: des, ST_OBJETIVO_CR: obj, ST_CARACT_CR: car}, function(response) {
                if (response) {
                    Notify('<?php echo utf8_encode("Atualizações feitas com sucesso."); ?>', 'bottom-right', '3000', 'palegreen', 'fa fa-check', true);
                }   
            });
            
        });
       
        $('#comp').bind('click', function() {
           $('#divPrincipal').hide();
           $('#divSecundario').hide();
           $('#infoCompl').show();
        }),
        
       $('#preview').bind('click', function() {
           $('#divSecundario').html('<div class="col-lg-6 col-sm-6 col-xs-12"><iframe src="http://docs.google.com/gview?url=http://www.bobbyaulas.com/aulas/application/cursos/'+$('#arquivo').html()+'&embedded=true" style="width:600px; height:500px;" frameborder="0"></iframe></div>');
           $('#divSecundario').show();
           $('#divPrincipal').hide();
           $('#infoCompl').hide();
       }), 
       
       $('#editar').bind('click', function() {
           //$('#divSecundario').html('<iframe src="http://docs.google.com/gview?url=http://www.yourwebsite.com/powerpoint.ppt&embedded=true" style="width:600px; height:500px;" frameborder="0"></iframe>');
           $('#divSecundario').hide();
           $('#divPrincipal').show();
           $('#infoCompl').hide();
       });
       
       $('#excluir').bind('click', function() {
           var modal = '<div class="modal-preview">\n\
                                            <div class="modal modal-primary">\n\
                                                <div class="modal-dialog">\n\
                                                    <div class="modal-content">\n\
                                                        <div class="modal-header">\n\
                                                            <button type="button" class="btnCancelar close" data-dismiss="modal" aria-hidden="true"><?php echo utf8_encode('×'); ?></button>\n\
                                                            <h4 class="modal-title"><?php echo utf8_encode('Confirmação'); ?></h4>\n\
                                                        </div>\n\
                                                        <div class="modal-body">\n\
                                                            <p>Certeza que deseja excluir o curso?</p>\n\
                                                        </div>\n\
                                                        <div class="modal-footer">\n\
                                                            <button type="button" class="btnCancelar btn btn-warning" data-dismiss="modal">Cancelar</button>\n\
                                                            <button type="button" id="btnExcluir" class="btn btn-primary">Aceitar</button>\n\
                                                        </div>\n\
                                                    </div><!-- /.modal-content -->\n\
                                                </div><!-- /.modal-dialog -->\n\
                                            </div><!-- /.modal -->\n\
                                        </div>';
                                                                
            $('#divModal').html(modal);
            $('#divModal').dialog({position: { my: "center", at: "center", of: $('#opcoes') }});
            fecharModal();
            excluirCurso();
            
            $('.ui-icon-closethick').hide();
       });
       
    });

</script>