
<div id="divModal"></div>
<?php

include_once '/decorators/form.php';
include_once '/forms/curso/editarslides.php';
include_once '/forms/curso/deleteslide.php';
include_once '/forms/curso/comp.php';

$curso = $this->curso;
?>

<?php $this->headScript()->appendFile($this->baseUrl('assets/js/informacoes_editar_curso.js')) ?>     

<div id="arquivo" style="display:none"><?php echo $curso[0]['ST_IDENT_CR']; ?></div>
<div id="curso" style="display:none"><?php echo $curso[0]['ID_ID_CR']; ?></div>

<div class="col-md-12">
        <div class="widget">
            <div class="widget-header" id="opcoes" style="height: 40px !important">
                <span class="widget-caption" style="margin-top:5px"> 
                    <a href="<?php echo $this->baseUrl().'/curso/novo' ?>" title="Novo curso">
                        <i class="fa fa-file" style="font-size:25px !important"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" id="editar" title="Editar">
                        <i class="fa fa-edit" style="font-size:25px !important"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" id="comp" title="<?php echo utf8_encode('Mais informações'); ?>">
                        <i class="glyphicon glyphicon-info-sign" style="font-size:25px !important"></i>
                    </a>&nbsp;
                    <a href="<?php echo $this->baseUrl('curso/ficha?curso='.$curso[0]['ID_ID_CR']); ?>" title="Ficha">
                        <i class="fa fa-files-o" style="font-size:25px !important"></i>&nbsp;
                    </a>  
                    <a href="javascript:void(0)" id="preview" title="Preview" style="padding-left:20px">
                        <i class="glyphicon glyphicon-eye-open" style="font-size:25px !important"></i>&nbsp;
                    </a>                    
                    <a href="javascript:void(0)" id="mudarVisibilidade" title="Mudar visibilidade">
                        <i class="fa fa-unlock-alt" style="font-size:25px !important"></i>&nbsp;
                    </a> 
                    <a href="javascript:void(0)" id="excluir" title="Excluir curso">
                        <i class="fa fa-trash-o" style="font-size:25px !important"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" id="usd" title="Ventas">
                        <i class="fa fa-usd" style="font-size:25px !important"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" title="Estatisticas" id="estatisticas">
                        <i class="glyphicon glyphicon-stats" style="font-size:25px !important"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" title="Usuarios" id="usr">
                        <i class="glyphicon glyphicon-user" style="font-size:25px !important"></i>&nbsp;
                    </a>                                                           
                </span>
            </div>
        </div>   
    </div>

<div id="divPrincipal">
    <?php
        $decform = new Decorators_Form();
        $form = new Forms_Curso_EditarSlides(array('titulo' => 'Editar curso: '.$curso[0]['ST_NOME_CR'], 'icone' => 'glyphicon glyphicon-edit'));
        $form->addDecorator($decform);
        $form->populate($curso[0]);
        echo $form;
    ?>
    
    <div class="col-lg-6 col-sm-6 col-xs-12">
        <div class="widget">
            <div class="widget-header bordered-bottom bordered-blue">
                    <span class="widget-caption" id="tituloForm"><i class="fa fa-book"></i>&nbsp;<?php  echo utf8_encode('Vista prévia da tela de Cursos'); ?></span>                        
           </div>
            <div class="widget-body">
                <div class="row">
                <?php
                $temCurso = Bobby_Sessao::temCurso($curso[0]['ID_ID_CR']);

        $icone = 'fa fa-pencil';
        $acao = 'Conferir';        
        $btnComprar = '';
        if ($curso[0]['VL_CUSTO_CR'] > 0 && !$temCurso) {
            $icone = 'fa fa-dollar';
            $acao = 'Comprar';
            $btnComprar = 'btnComprar';
        }
        ?>
            <div class="col-sm-5 col-md-7">
              <div class="thumbnail">
                  <img data-src="holder.js/100%x200" alt="100%x200" src="<?php echo $this->baseUrl().'/../application/uploads/'.$curso[0]['ST_IMAGEM_CR']; ?>" data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                  <div class="caption" style="background-color: #F0F0F0 ">
                  <h3 style="margin-top: 0px"><?php echo $curso[0]['ST_NOME_CR']; ?></h3>
                  <p><?php echo $curso[0]['ST_SUBTITULO_CR']; ?></p>
                  <?php
                  if ($curso[0]['VL_CUSTO_CR'] > 0) {
                      echo '<span class="price palegreen" style="font-size:15px"><b>R$ '.$curso[0]['VL_CUSTO_CR'].'</b></span>';
                  } else {
                      echo '<span style="color: green"><b>GRATIS</b></span>';
                  }
                  ?>
                  <p><br><span><a class="btn btn-primary" style="margin-right:5px" href="javascript:void(0)"><i class="fa fa-info"></i> Ficha</a><span id="btn<?php echo $curso[0]['ID_ID_CR']; ?>"><a href="javascript:void(0)" class="btn btn-success <?php echo $btnComprar ?>" role="button"><i class="<?php echo $icone; ?>"></i><?php echo $acao; ?></a></span></span></p>
                </div>
              </div>
            </div>
            </div>
                </div>
        </div>
    </div>    
</div>
<div id="divSecundario"></div>
<div id="divFormExcluir" style="display:none;">
    <?php
        $formExcluir = new Forms_Curso_DeleteSlide();
        $formExcluir->addDecorator($decform);
        $formExcluir->populate($curso[0]);
        echo $formExcluir;   
    ?>
</div>

<div id="infoCompl" style="display:none;">
    
    <?php
        $formComp = new Forms_Curso_Comp(array('titulo' => 'Mais informações', 'icone' => 'glyphicon glyphicon-info-sign'));
        $formComp->addDecorator($decform);
        $formComp->populate($curso[0]);
        echo $formComp;      
    ?> 
</div>

<div id="divAdicionar_usuario" style="display:none">  
    
    <?php
        include_once APPLICATION_PATH.'/forms/curso/AdUsuario.php';
        $form_adicionarUsuario = new Forms_Curso_AdUsuario(array('titulo' => 'Adicionar usuario ao curso','width' => '400px'));
        $form_adicionarUsuario->addDecorator($decform);
        echo $form_adicionarUsuario;
    ?>
</div>

<div id="infoVentas" style="display:none;">
    
</div>
<!--<a href="javascript:void(0);" id="adicionar_usuario">-->
<div id="infoUsers" style="display:none">
    
<!--    <div class="col-lg-2 col-sm-4 col-xs-6">
                                    <div class="databox databox-lg databox-vertical databox-inverted bg-white databox-shadowed">
                                        <div class="databox-top">
                                            <div class="databox-piechart">
                                                <div data-toggle="easypiechart" class="easyPieChart block-center" data-barcolor="#e75b8d" data-linecap="butt" data-percent="40" data-animate="500" data-linewidth="8" data-size="100" data-trackcolor="#eee" style="width: 100px; height: 100px; line-height: 100px;">
                                                    <span class="white font-200"><i class="fa fa-user green" style="font-size:100px"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="databox-bottom no-padding text-align-center">
                                            <span class="databox-number lightcarbon no-margin">&nbsp;</span>
                                            <span class="databox-text lightcarbon no-margin">ADICIONAR USUARIO</span>

                                        </div>
                                    </div>
                                </div>-->
</div>
<!--        </a>-->

<div id="divGraficas" style="display:none">
    
    
    <div class="col-lg-12 col-sm-6 col-xs-12">
                                    <div class="tabbable">
                                        <ul class="nav nav-tabs" id="myTab">
                                            <li class="active">
                                                <a data-toggle="tab" href="#home">
                                                    Cursos/Mes
                                                </a>
                                            </li>

                                            <li class="tab-red">
                                                <a data-toggle="tab" href="#profile">
                                                    Profile
                                                </a>
                                            </li>

                                        </ul>

                                        <div class="tab-content">
                                            <div id="home" class="tab-pane in active">
                                                <p>
                                                
                                                <div class="row">
                        <div class="col-xs-12 col-md-12 col-lg-12">
                            <div class="widget">
                                <div class="widget-header">
<!--                                    <span class="widget-caption">Ventas Cursos/Mes</span>-->
                             
                                </div>
                                <div class="widget-body">

                                    <div class="row">
                                        <div class="col-sm-12">
                                            <div id="selectable-chart" class="chart chart-lg" style="padding: 0px; position: relative;">
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                                                
                                                
                                               
                                            </div>

                                            <div id="profile" class="tab-pane">
                                                <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid.</p>
                                            </div>

                                        </div>
                                    </div>
                                    <div class="horizontal-space"></div>

                                </div>
    
</div>

<script type="text/javascript">
    
    function fecharModal() {
        $('.btnCancelar').bind('click', function() {
            $('#divModal').dialog('destroy');
        });
    }
    
    function excluirCurso() {
        $('#btnExcluir').bind('click', function() {
           $('#formExcluir').submit(); 
        });
    }
    
    $(function() {
       var curso = $('#curso').html();
        
        $('#estatisticas').bind('click', function() {
           $('#divGraficas').show(); 
            $('#infoUsers').hide(); 
            $('#infoVentas').hide();
            $('#divPrincipal').hide();
            $('#divSecundario').hide();
            $('#infoCompl').hide();    
            $.post('dadosgraficacomprascursos', {curso: curso}, function(response) {
             //   console.log(response);                
                dados = [];
                $.each(response, function(key, val) {
                    valores = [];
                    valores.push(val['Mes']);
                    valores.push(val['Qant']);
                    dados.push(valores);
                })
                InitiateFlotSelectableChart.init(dados);
                console.log(dados);
            });
            
        });
        
        $('#adicionar_usuario').bind('click', function() {
            $('#divAdicionar_usuario').dialog({position: { my: "center", at: "center", of: $('#opcoes') }});
        });
        
        $('#usr').bind('click', function() {
            $.post('usuariosdelcurso', {curso: curso}, function(response) {
                var obj = $('#infoUsers');
                var html = obj.html();
                for(var i = 0; i < response.length; i++) {
                    html += ' <div class="col-lg-2 col-sm-4 col-xs-6">\n\
                                    <div class="databox databox-lg databox-vertical databox-inverted bg-white databox-shadowed">\n\
                                        <div class="databox-top">\n\
                                            <div class="databox-piechart">\n\
                                                <div data-toggle="easypiechart" class="easyPieChart block-center" data-barcolor="#e75b8d" data-linecap="butt" data-percent="40" data-animate="500" data-linewidth="8" data-size="100" data-trackcolor="#eee" style="width: 100px; height: 100px; line-height: 100px;">\n\
                                                    <span class="white font-200"><i class="fa fa-user blue" style="font-size:100px"></i></span>\n\
                                                </div>\n\
                                            </div>\n\
                                        </div>\n\
                                        <div class="databox-bottom no-padding text-align-center">\n\
                                            <span class="databox-number lightcarbon no-margin">&nbsp;</span>\n\
                                            <span class="databox-text lightcarbon no-margin">'+response[i].ST_USUARIO_USU+'</span>\n\
                                        </div>\n\
                                    </div>\n\
                                </div>';
                                obj.html(html);               
                }
            });
            $('#infoUsers').show(); 
            $('#infoVentas').hide();
            $('#divPrincipal').hide();
            $('#divSecundario').hide();
            $('#infoCompl').hide();           
        });
        
        
        $('#usd').bind('click', function() {
           $('#infoVentas').html('');
           $.post('ventas', {curso: $('#curso').html()}, function(response){
                $('#infoVentas').show();
                $('#divPrincipal').hide();
                $('#divSecundario').hide();
                $('#infoCompl').hide();  
                var html;
                var usr;
                for (var i = 0; i < response.length; i++) {
                    html = $('#infoVentas').html();
                    
                    usr = '<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">\n\
    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">\n\
        <div class="databox-left bg-green" style="weight:100px !important; height:100px !important;">\n\
            <div class="databox-icon">\n\
                <i class="fa fa-user"></i>\n\
            </div> \n\
        </div>\n\
        <div class="databox-right">\n\
            <span class="databox-number green">'+response[i].ST_USUARIO_USU+'</span>\n\
            <div class="databox-text darkgray">'+response[0].DT_DATA_COM+'</div>\n\
            <div class="databox-stat green radius-bordered">\n\
                <i class="stat-icon icon-lg fa fa-tasks"></i>\n\
            </div>\n\
        </div>\n\
    </div>\n\
</div> ';
                    html += usr;
                    $('#infoVentas').html(html);
                }
           });
        });
        
        $('#btnAtualizarComp').bind('click', function() {
            var des = $('#ST_DESCR_CR').val();
            var obj = $('#ST_OBJETIVO_CR').val();
            var cont = $('#ST_CONTEUDO_CR').val();
            var car = $('#ST_CARACT_CR').val();
            $.post("atualizarslidecomp", {curso: curso , ST_CONTEUDO_CR: cont, ST_DESCR_CR: des, ST_OBJETIVO_CR: obj, ST_CARACT_CR: car}, function(response) {
                if (response) {
                    Notify('<?php echo utf8_encode("Atualizações feitas com sucesso."); ?>', 'bottom-right', '3000', 'palegreen', 'fa fa-check', true);
                }   
            });
            
        });
       
        $('#comp').bind('click', function() {
           $('#divPrincipal').hide();
           $('#divSecundario').hide();
           $('#infoVentas').hide();
           $('#infoCompl').show();
           start_informacoes_editar_curso();
        }),
        
       $('#preview').bind('click', function() {
           $('#divSecundario').html('<div class="col-lg-6 col-sm-6 col-xs-12"><iframe src="http://docs.google.com/gview?url=http://www.bobbyaulas.com/aulas/application/cursos/'+$('#arquivo').html()+'&embedded=true" style="width:600px; height:500px;" frameborder="0"></iframe></div>');
           $('#divSecundario').show();
           $('#divPrincipal').hide();
           $('#infoCompl').hide();
           $('#infoVentas').hide();
       }), 
       
       $('#editar').bind('click', function() {
           //$('#divSecundario').html('<iframe src="http://docs.google.com/gview?url=http://www.yourwebsite.com/powerpoint.ppt&embedded=true" style="width:600px; height:500px;" frameborder="0"></iframe>');
           $('#divSecundario').hide();
           $('#divPrincipal').show();
           $('#infoCompl').hide();
           $('#infoVentas').hide();
       });
       
       $('#excluir').bind('click', function() {
           var modal = '<div class="modal-preview">\n\
                                            <div class="modal modal-primary">\n\
                                                <div class="modal-dialog">\n\
                                                    <div class="modal-content">\n\
                                                        <div class="modal-header">\n\
                                                            <button type="button" class="btnCancelar close" data-dismiss="modal" aria-hidden="true"><?php echo utf8_encode('×'); ?></button>\n\
                                                            <h4 class="modal-title"><?php echo utf8_encode('Confirmação'); ?></h4>\n\
                                                        </div>\n\
                                                        <div class="modal-body">\n\
                                                            <p>Certeza que deseja excluir o curso?</p>\n\
                                                        </div>\n\
                                                        <div class="modal-footer">\n\
                                                            <button type="button" class="btnCancelar btn btn-warning" data-dismiss="modal">Cancelar</button>\n\
                                                            <button type="button" id="btnExcluir" class="btn btn-primary">Aceitar</button>\n\
                                                        </div>\n\
                                                    </div><!-- /.modal-content -->\n\
                                                </div><!-- /.modal-dialog -->\n\
                                            </div><!-- /.modal -->\n\
                                        </div>';
                                                                
            $('#divModal').html(modal);
            $('#divModal').dialog({position: { my: "center", at: "center", of: $('#opcoes') }});
            fecharModal();
            excluirCurso();
            
            $('.ui-icon-closethick').hide();
       });
       
    });

</script>