<?php

$cursos = $this->cursos;

?>

<?php 
    foreach ($cursos as $curso) {
        if ($curso['FL_DISPONIVEL_CR'] == 1) {
            $icone = 'fa fa-unlock';
            $title = "Visivel";
        } else {
            $icone = 'fa fa-lock';
            $title ="Nao visivel";
        }
?>

<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
        <div class="databox-left bg-purple" style="weight:100px !important; height:100px !important;">
            <div class="databox-icon">
                <i class="fa fa-book"></i>
            </div> 
        </div>
        <div class="databox-right">
            <span class="databox-number purple" id="curso" data-curso="<?php echo $curso['ID_ID_CR']; ?>"><a href="<?php echo $this->baseUrl().'/curso/cursoslideedit?curso='.$curso['ID_ID_CR']; ?>"><?php echo $curso['ST_NOME_CR']; ?></a></span>
            <div class="databox-text darkgray"></div>
            <div class="databox-stat purple radius-bordered"><a href="javascript:void(0)" data-visibilidade="<?php echo $curso['FL_DISPONIVEL_CR']; ?>" id="mudarVisibilidade">
                <i title="<?php echo $title; ?>" id="iconeVis" class="stat-icon icon-lg <?php echo $icone; ?>"></i>
            </a></div>
        </div>
    </div>
</div>
<div id="divModal"></div>

<?php
    }
?>
<script type="text/javascript" src="<?php echo $this->baseUrl('assets/js/modal.js'); ?>" ></script>