<?php

include APPLICATION_PATH.'/Elementoshtml/Alerts.php';
include APPLICATION_PATH.'/Forms/Anotacoes.php';
include APPLICATION_PATH.'/Forms/Pergunta.php';
include APPLICATION_PATH.'/Decorators/Form.php';

$quantidade = $this->quantidade_slides;

$slide = $this->slide;
$anotacoes = $this->anotacoes;
$perguntas = $this->perguntas;
$respostas = $this->respostas;
if (!empty($anotacoes)) {
    $anotacoes = $anotacoes[0];
}

$temPerguntas = false;
if (!empty($perguntas)) {
    $temPerguntas = true;
}

if (count($slide)> 0) {
    $slide = $slide[0];
?>

<input type="hidden" id="quantidade" value="<?php echo $quantidade; ?>" />
<input type="hidden" id="curso" value="<?php echo $slide['ID_CURSO_CR']; ?>" />
<input type="hidden" id="slide" value="<?php echo $slide['NM_SLIDE_SLI']; ?>" />
<input type="hidden" id="respostas" value='<?php echo $respostas; ?>' />
<input type="hidden" id="verdadeiras" value='<?php echo $slide['ST_RESPOSTAS_SLI']; ?>' />

<div class="col-lg-7 col-sm-6 col-xs-12">
    <div class="well with-header" style="height: 510px">
        <div class="header bordered-pink">
            
            <span style="float: left">
            
                <a id="ant" href="javascript:void(0);" title="Anterior">
                    <i class="fa-hover fa fa-angle-double-left"></i>
                </a>

            </span>    
            
            <?php
                echo '<center>';
                for ($i = 1; $i <= $quantidade; $i++) {
                    
                    $color = '';
                    if ($i == $slide['NM_SLIDE_SLI']) {
                         $color = 'primary';
                    } else {
                         $color = 'default';
                    }
                    echo '<a href="javascript:void(0)" class="quadslide" data-slide='.$i.'><span id="quad_'.$i.'" class="badge badge-'.$color.' badge-square" style="margin-right: 7px; margin-right: 7px;">'.$i.'</span></a>';
                }
                echo '</center>';
            ?>
            
            <span style="float: right">

                <a id="sig" href="javascript:void(0);" title="Seguinte">
                    <i class=" fa-hover fa fa-angle-double-right"></i>
                </a>

            </span>
        
            <center>
                
               <?php echo '<span style="font-size: 15px"><b>'.$slide['ST_NOME_CR'].'</b></span><br><span id="tituloslide">'.$slide['ST_TITULO_SLI'].'</span>'; ?>
        
            </center>
        </div>
        <div class="col-lg-12 container" style="padding-top:25px"><span id="htmlslide"><?php echo $slide['ST_SLIDE_SLI']; ?></span></div> 
    </div>
</div>


<?php

    $decform = new Decorators_Form();
    $formAanotacoes = new Forms_Anotacoes(array('titulo' => 'Anotacoes', 'class' => 'col-lg-5 col-sm-6 col-xs-10'));
    $formAanotacoes->populate($anotacoes);
    $formAanotacoes->addDecorator($decform);

    echo $formAanotacoes;
    
?>

<div class="col-lg-5 col-sm-6 col-xs-10">
    <div class="widget-body">
        Correicoes <span id="vlCorretas">0</span>/<span id="vlExercicios">0</span>
    </div>
</div>


<?php

} else {
    $msg = new Elementoshtml_Alerts();
    echo $msg->warning("Nao existe nenhuma slide cadastrada para o curso.");
}

?>


<div class="row">
                                <div class="col-lg-12">
                                    <div class="widget">
                                        <div class="widget-header bordered-bottom bordered-themesecondary">
                                            <i class="widget-icon fa fa-question-circle themesecondary"></i>
                                            <span class="widget-caption themesecondary">Preguntas</span>
                                        </div><!--Widget Header-->
                                        
                                    <div class="panel-group accordion" id="accordions" style="margin: 0px 0px 0px 0px !important">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordions" href="#collapseOnes" aria-expanded="false">
                                                        <i class="fa-fw fa fa-check"></i> Nova pergunta...
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseOnes" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                                <div class="panel-body border-red">
                                                    <?php
                                                    
                                                        $parametros = array('ID_CURSO_CR' => $this->idcurso, 'ID_USUARIO_USU' => $this->idusuario);
                                                        $formPerguntar = new Forms_Pergunta();
                                                        $formPerguntar->populate($parametros);
                                                        echo $formPerguntar;
                                                    
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                       
                                    </div>

                                        <div class="widget-body  no-padding">
                                            <div class="tickets-container">
                                                <ul class="tickets-list">
                                                  
                                                        
                                                            <?php
                                                          
                                                            if ($temPerguntas) {
                                                            
                                                                $collapsed = 0;
                                                                foreach ($perguntas as $pergunta) { 
                                                                    
                                                                    if (!$pergunta['FL_EXCLUIDA_PER']) {
                                                                    $respondida = !(empty($pergunta['ST_RESPOSTA_PER']));
                                                                    $resultado = "Aguardando resposta";
                                                                    if ($respondida) {
                                                                        $resultado = "RESPONDIDA";
                                                                    }
                                                                ?>
                                                    
                                                      <li class="ticket-item">
                                                        
                                                        <div class="row">
                                                    
                                                    <div class="ticket-user col-lg-6 col-sm-12">
                                                          <!--          <img src="assets/img/avatars/adam-jansen.jpg" class="user-avatar">-->
                                                                    <span class="user-name"><div class="widget-buttons buttons-bordered">
                                                <a href="javascript:void(0)" id="btnExcluirPergunta" valor="<?php echo $pergunta['ID_PERGUNTA_PER']; ?>" class="btnExcluir"><i class="fa fa-times red"></i></a>
                                            </div><?php echo $pergunta['ST_PERGUNTA_PER']; ?></span>
                                                                  <?php if ($respondida) {
                                                                      
                                                                  }?>
                                                                </div>
                                                                <div class="ticket-time  col-lg-4 col-sm-6 col-xs-12">
                                                                    <div class="divider hidden-md hidden-sm hidden-xs"></div>
                                                                   
                                                                                <i class="fa fa-clock-o"></i>
                                                                                <span class="time"><?php echo $pergunta['DT_UTIMOMOV_PER']; ?></span>                                                                        
                                                                     



                                                                </div>
                                                                <div class="ticket-type  col-lg-2 col-sm-6 col-xs-12">
                                                                    <span class="divider hidden-xs"></span>
                                                                    <span class="type"><?php echo $resultado; ?></span>
                                                                </div>

                                                                <?php 
                                                                    if ($respondida) {
                                                                    ?>
                                                                        <div class="ticket-state bg-palegreen">
                                                                            <i class="fa fa-check"></i>
                                                                        </div> <?php
                                                                    } else {
                                                                        ?>
                                                                            <div class="ticket-state bg-yellow">
                                                                                <i class="fa fa-info"></i>
                                                                            </div> <?php                                                                    
                                                                    }
                                                                  ?>   <?php
                    ?></div>
                                                       
                                                    </li>
                                                        
                                                                                            <div class="panel-group accordion" id="accordions" style="margin: 0px 0px 0px 0px !important">

                                       
                                    </div> <?php
                                    
                                    
                                    
                                    if ($respondida) {
                                        ?>
                                    
                                            <div class="panel panel-default">
                                                        <div class="panel-heading">
                                                            <h4 class="panel-title">
                                                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="<?php echo '#collapsed'.$collapsed; ?>" aria-expanded="false">
                                                                    Resposta
                                                                </a>
                                                            </h4>
                                                        </div>
                                                        <div id="<?php echo 'collapsed'.$collapsed; ?>" class="panel-collapse collapse" aria-expanded="false">
                                                            <div class="panel-body border-palegreen">
                                                                <?php echo $pergunta['ST_RESPOSTA_PER']; ?>
                                                            </div>
                                                        </div>
                                                    </div>  
                                                   <?php 
                                                   
                                    }
                                    $collapsed++;
                                                    
                                                    
                                                                }         
                                                            } }else {
                                                                $elemento = new Elementoshtml_Alerts();
                                                                echo $elemento->warning("Nao tem perguntas.");
                                                            }
                                                            ?>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>

<script type="text/javascript">
    
    function quadrados(actual) {
        var default_ = 'badge badge-default badge-square';
        var primary = 'badge badge-primary badge-square';
        
        $('.badge').removeClass().addClass(default_);      
        $('#quad_'+actual).removeClass('badge-default').addClass('badge-primary');
    }
    
    function exercicios() {
       
        $('#btnRespostas').bind('click', function() {
            var curso = $('#curso').val();
            var slide = $('#slide').val();
            $.post('respostas', {slide: slide, curso: curso}, function(dados) {
                var respostas = dados.respostas[0].ST_RESPOSTAS_USC;
                var verdadeiras = dados.verdadeiras[0].ST_RESPOSTAS_SLI;
                var valores_verdadeiras = JSON.parse(verdadeiras);
                var valores_respostas = JSON.parse(respostas);
                var perguntas = 0;
                var corretas = 0;
                
                $.each(valores_verdadeiras, function(key, value) { 
                    perguntas = perguntas + 1;
                    $.each(valores_respostas, function(key2, value2) {
                        
                        if (key == key2) {
                            var selector = '';
                            var selector_out = '';
                            if (value == value2) {
                                selector = '#'+key+'_check'; 
                                selector_out = '#'+key+'_times';
                                corretas = corretas + 1;
                                $('#respCorreta_'+key).html('');
                            } else {
                                selector = '#'+key+'_times';
                                selector_out = '#'+key+'_check';
                                $('#respCorreta_'+key).html(value);
                            }
                            $(selector).attr('style','');
                            $(selector_out).attr('style','display:none');
                            $('#'+key).val(value2);
                                                            
                        }
                    });
                });   
                $('#vlCorretas').html(parseInt($('#vlCorretas').html())+corretas);
                $('#vlExercicios').html(parseInt($('#vlExercicios').html())+perguntas);
            });
        });
        
        $('#btnCorregir').bind('click', function() {
            var curso = $('#curso').val();
            var slide = $('#slide').val();
     
            var arr = {};
            
            $.post("respostas", {slide: slide, curso: curso}, function(dados) {
                var resp = dados.verdadeiras[0].ST_RESPOSTAS_SLI;
                var valores = JSON.parse(resp);
                
                $.each(valores, function(key, value) {
                    var selector = '#'+key;
                    arr[key] = $(selector).val();
                });
                var jsonarr = JSON.stringify(arr);
                $.post("enviarrespostas", {ST_RESPOSTAS_USC: jsonarr, ID_SLIDE_USC: slide, ID_CURSO_USC: curso }, function(response) {
                    $('#btnRespostas').trigger('click');
                });
            });
            
        });
    }
    
    function verificarRespostas() {
        var respostas = $('#respostas').val();
        
        if (respostas !== '') {
            var verdadeiras = $('#verdadeiras').val();
            var valores_verdadeiras = JSON.parse(verdadeiras);
            var valores_respostas = JSON.parse(respostas);
            var perguntas = 0;
            var corretas = 0;

            $.each(valores_verdadeiras, function(key, value) { 
                perguntas = perguntas + 1;
                $.each(valores_respostas, function(key2, value2) {

                    if (key == key2) {
                        var selector = '';
                        var selector_out = '';
                        if (value == value2) {
                            selector = '#'+key+'_check'; 
                            selector_out = '#'+key+'_times';
                            corretas = corretas + 1;
                            $('#respCorreta_'+key).html('');
                        } else {
                            selector = '#'+key+'_times';
                            selector_out = '#'+key+'_check';
                            $('#respCorreta_'+key).html(value);
                        }
                        $(selector).attr('style','');
                        $(selector_out).attr('style','display:none');
                        $('#'+key).val(value2);

                    }
                });
            });   
            $('#vlCorretas').html(parseInt($('#vlCorretas').html())+corretas);
            $('#vlExercicios').html(parseInt($('#vlExercicios').html())+perguntas);    
            $('#btnCorregir').css("display","none");
            $('#btnRespostas').css("display","none");            
        }
    };
    
    $(function() {
      
        verificarRespostas();
        exercicios();
        
        $('.quadslide').bind('click', function() {
            var slide = $(this).data('slide');
            $('#slide').val(slide - 1);
            $('#sig').trigger('click');
        });
        
        $('.btnExcluir').bind('click', function() {
            var pergunta = $(this).attr('valor'); 
            var excluir_pergunta = confirm('Deseja excluir a pergunta?');
            if (excluir_pergunta) {
                $.post("../perguntas/excluirpergunta", {ID_PERGUNTA_PER: pergunta}, function(dados) {
                   window.location.reload();
                });
            }
        });
        
        $('#Gravar').bind('click',function() {
            var curso = $('#curso').val();
            var anotacoes = $('#ST_TEXTO_ANO').val();
            var usuario = 1;
            
            $.post("gravaranotacoes", {ID_CURSO_CR : curso, ID_USUARIO_USU: usuario, ST_TEXTO_ANO: anotacoes}, function(data) {
                $('#tituloForm').html('Anotacoes <span style="width: 6px">&nbsp;&nbsp;&nbsp; utima modificao: '+ data +' </span>');
            });
        });
        
        $('#sig').bind('click', function() {     
            var curso = $('#curso').val();
            var slide = parseInt($('#slide').val())+1;
            
            $.post("vercursojson", {curso : curso, slide: slide}, function(data) {
                    var resposta = data.ST_RESPOSTAS_USC;
                    if (resposta !== '') {
                        resposta = data.ST_RESPOSTAS_USC[0].ST_RESPOSTAS_USC;
                    }
                    
                    quadrados(slide);
                    
                    $('#htmlslide').html(data[0].ST_SLIDE_SLI);
                    $('#numeroslide').html(data[0].NM_SLIDE_SLI);
                    $('#tituloslide').html(data[0].ST_TITULO_SLI);
                    $('#verdadeiras').html(data[0].ST_RESPOSTAS_SLI);
                    $('#respostas').val(resposta);
                    $('#slide').val(slide);
                    verificarRespostas();
                    exercicios();
            });
        });
        
        $('#ant').bind('click', function() {     
            var curso = $('#curso').val();
            var slide = parseInt($('#slide').val())-1;
            
            $.post("vercursojson", {curso : curso, slide: slide}, function(data) {
                    var resposta = data.ST_RESPOSTAS_USC;
                    if (resposta !== '') {
                        resposta = data.ST_RESPOSTAS_USC[0].ST_RESPOSTAS_USC;
                    }
                    $('#htmlslide').html(data[0].ST_SLIDE_SLI);   
                    $('#numeroslide').html(data[0].NM_SLIDE_SLI);
                    $('#tituloslide').html(data[0].ST_TITULO_SLI);
                    $('#slide').val(slide);
                    $('#verdadeiras').html(data[0].ST_RESPOSTAS_SLI);
                    $('#respostas').val(resposta);
                    verificarRespostas();
                    exercicios();
            });
        });        
    });
    
    
    
</script>    

