<?php

include APPLICATION_PATH.'/Elementoshtml/Alerts.php';
include APPLICATION_PATH.'/Forms/Anotacoes.php';
include APPLICATION_PATH.'/Forms/Pergunta.php';
include APPLICATION_PATH.'/Decorators/Form.php';

$slide = $this->slide;
$quantidade = $this->quantidade_slides;
$quadrados_quantidade = $quantidade;


$anotacoes = $this->anotacoes;
$perguntas = $this->perguntas;
$respostas = $this->respostas;

$usuario_curso = $this->usuario_curso;

if (!empty($anotacoes)) {
    $anotacoes = $anotacoes[0];
}

$temPerguntas = false;
if (!empty($perguntas)) {
    $temPerguntas = true;
}

if (count($slide)> 0) {
    $slide = $slide[0];

    $actual = $slide['NM_SLIDE_SLI'];
    $i = 1;

    if ($quadrados_quantidade > 14) {
        $quadrados_quantidade = 14;
    }


    switch ($actual) {
        case $actual < 8:
            break;
        case $actual >= 8;
            $aux = $actual + 8;
            if ($aux < $quantidade) {
                $i = $actual - 7;
                $quadrados_quantidade = $actual + 8;
            } else {
                $quadrados_quantidade = $quantidade;
                $i = $quantidade - 14;
            }
            break;
    }

?>

<input type="hidden" id="quantidade" value="<?php echo $quantidade; ?>" />
<input type="hidden" id="quadrados_quantidade" value="<?php echo $quadrados_quantidade; ?>" />
<input type="hidden" id="indice" value="<?php echo $i; ?>" />
<input type="hidden" id="curso" value="<?php echo $slide['ID_CURSO_CR']; ?>" />
<input type="hidden" id="slide" value="<?php echo $slide['NM_SLIDE_SLI']; ?>" />
<input type="hidden" id="respostas" value='<?php echo $respostas; ?>' />
<input type="hidden" id="verdadeiras" value='<?php echo $slide['ST_RESPOSTAS_SLI']; ?>' />

<div class="col-md-7 col-sm-6 col-xs-18">
    <div class="well with-header" style="height: 510px">
        <div class="header bordered-pink">
            
            <span style="float: left">
            
                <a id="inicio" href="javascript:void(0);" title="Inicio">
                    <i class="fa-hover fa fa-angle-double-left"></i>
                </a>

                <a id="ant" href="javascript:void(0);" title="Anterior">
                    <i class="fa-hover fa fa-angle-left"></i>
                </a>
                
            </span>    
            
           
            
            <span style="float: right">

                <a id="sig" href="javascript:void(0);" title="Seguinte">
                    <i class=" fa-hover fa fa-angle-right"></i>
                </a>
                
                
                <a id="fim" href="javascript:void(0);" title="Fim">
                    <i class=" fa-hover fa fa-angle-double-right"></i>
                </a>

            </span>
        
            <center>
                
               <?php echo '<span style="font-size: 15px"><b>'.$slide['ST_NOME_CR'].'</b></span><br><span id="tituloslide">'.$slide['ST_TITULO_SLI'].'</span>'; ?>
        
            </center>
            
             <?php
                echo '<div id="divQuadrantes"><center>';
                for ($i; $i <= $quadrados_quantidade; $i++) {
                    
                    $color = '';
                    if ($i == $slide['NM_SLIDE_SLI']) {
                         $color = 'primary';
                    } else {
                         $color = 'default';
                    }
                    echo '<a href="javascript:void(0)" class="quadslide" data-slide='.$i.'><span id="quad_'.$i.'" class="quadclass badge badge-'.$color.' badge-square" style="margin-right: 7px; margin-right: 7px;">'.$i.'</span></a>';
                }
                echo '</center></div>';
            ?>
        </div>
        <div class="col-lg-12 container" style="padding-top:25px"><span id="htmlslide"><?php echo $slide['ST_SLIDE_SLI']; ?></span></div> 
    </div>
</div>


<?php

    $decform = new Decorators_Form();
//    include_once APPLICATION_PATH.'/decorators/textarea.php';
    $formAanotacoes = new Forms_Anotacoes(array('titulo' => 'Anotacoes', 'class' => 'col-md-5 col-sm-6 col-xs-18', 'icone' => 'fa fa-pencil-square-o'));
    $formAanotacoes->populate($anotacoes);
    $formAanotacoes->addDecorator($decform);

    echo $formAanotacoes;
    
?>

<div class="col-lg-5 col-md-3 col-sm-6 col-xs-10">
                                    <div class="databox bg-white radius-bordered">
                                        <div class="databox-left bg-themeprimary">
                                            <div class="databox-piechart">
                                                <div id="users-pie" data-toggle="easypiechart" class="easyPieChart" data-barcolor="#fff" data-linecap="butt" data-percent="80" data-animate="500" data-linewidth="3" data-size="47" data-trackcolor="rgba(255,255,255,0.1)" style="width: 47px; height: 47px; line-height: 47px;"><span class="white font-90"><h2><div id="vlPorcentagemExercicios">
                                                <?php
        
                                                    if ($usuario_curso['NM_TOTALEXERC_UC'] == 0 ||  $usuario_curso['NM_ACERTOS_UC'] == 0) {
                                                        echo '0';
                                                    } else {
                                                        echo intval(($usuario_curso['NM_ACERTOS_UC']*100)/$usuario_curso['NM_TOTALEXERC_UC']);
                                                    }
                                                
                                                
                                                    ?>%</div></h2></span><canvas width="47" height="47"></canvas></div>
                                            </div>
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number themeprimary"><span id="vlCorretas"><?php echo $usuario_curso['NM_ACERTOS_UC']; ?></span>/<span id="vlExercicios"><?php echo $usuario_curso['NM_TOTALEXERC_UC']; ?></span></span>
                                            <div class="databox-text darkgray">EXERCICIOS</div>
                                            <div class="databox-state bg-themeprimary">
                                                <i class="fa fa-pencil"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>


<!--<div class="col-lg-5 col-sm-6 col-xs-10">
    <div class="widget-body">
        Correicoes 
    </div>
</div>-->


<?php

} else {
    $msg = new Elementoshtml_Alerts();
    echo $msg->warning("Nao existe nenhuma slide cadastrada para o curso.");
}

?>


<div class="row">
                                <div class="col-lg-12">
                                    <div class="widget">
                                        <div class="widget-header bordered-bottom bordered-themesecondary">
                                            <i class="widget-icon fa fa-question-circle themesecondary"></i>
                                            <span class="widget-caption themesecondary">Preguntas</span>
                                        </div><!--Widget Header-->
                                        
                                    <div class="panel-group accordion" id="accordions" style="margin: 0px 0px 0px 0px !important">
                                        <div class="panel panel-default">
                                            <div class="panel-heading">
                                                <h4 class="panel-title">
                                                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordions" href="#collapseOnes" aria-expanded="false">
                                                        <i class="fa-fw fa fa-check"></i> Nova pergunta...
                                                    </a>
                                                </h4>
                                            </div>
                                            <div id="collapseOnes" class="panel-collapse collapse" aria-expanded="false" style="height: 0px;">
                                                <div class="panel-body border-red">
                                                    <?php
                                                    
                                                        $parametros = array('ID_CURSO_CR' => $this->idcurso, 'ID_USUARIO_USU' => $this->idusuario);
                                                        $formPerguntar = new Forms_Pergunta();
                                                        $formPerguntar->populate($parametros);
                                                        echo $formPerguntar;
                                                    
                                                    ?>
                                                </div>
                                            </div>
                                        </div>
                                       
                                    </div>

                                        <div class="widget-body  no-padding">
                                            <div class="tickets-container">
                                                <ul class="tickets-list">
                                                  
                                                        
                                                            <?php
                                                          
                                                            if ($temPerguntas) {
                                                            
                                                                $collapsed = 0;
                                                                foreach ($perguntas as $pergunta) { 
                                                                    
                                                                    if (!$pergunta['FL_EXCLUIDA_PER']) {
                                                                    $respondida = !(empty($pergunta['ST_RESPOSTA_PER']));
                                                                    $resultado = "Aguardando resposta";
                                                                    if ($respondida) {
                                                                        $resultado = "RESPONDIDA";
                                                                    }
                                                                ?>
                                                    
                                                      <li class="ticket-item">
                                                        
                                                        <div class="row">
                                                    
                                                    <div class="ticket-user col-lg-6 col-sm-12">
                                                          <!--          <img src="assets/img/avatars/adam-jansen.jpg" class="user-avatar">-->
                                                                    <span class="user-name"><div class="widget-buttons buttons-bordered">
                                                <a href="javascript:void(0)" id="btnExcluirPergunta" valor="<?php echo $pergunta['ID_PERGUNTA_PER']; ?>" class="btnExcluir"><i class="fa fa-times red"></i></a>
                                            </div><?php echo $pergunta['ST_PERGUNTA_PER']; ?></span>
                                                                  <?php if ($respondida) {
                                                                      
                                                                  }?>
                                                                </div>
                                                                <div class="ticket-time  col-lg-4 col-sm-6 col-xs-12">
                                                                    <div class="divider hidden-md hidden-sm hidden-xs"></div>
                                                                   
                                                                                <i class="fa fa-clock-o"></i>
                                                                                <span class="time"><?php echo $pergunta['DT_UTIMOMOV_PER']; ?></span>                                                                        
                                                                     



                                                                </div>
                                                                <div class="ticket-type  col-lg-2 col-sm-6 col-xs-12">
                                                                    <span class="divider hidden-xs"></span>
                                                                    <span class="type"><?php echo $resultado; ?></span>
                                                                </div>

                                                                <?php 
                                                                    if ($respondida) {
                                                                    ?>
                                                                        <div class="ticket-state bg-palegreen">
                                                                            <i class="fa fa-check"></i>
                                                                        </div> <?php
                                                                    } else {
                                                                        ?>
                                                                            <div class="ticket-state bg-yellow">
                                                                                <i class="fa fa-info"></i>
                                                                            </div> <?php                                                                    
                                                                    }
                                                                  ?>   <?php
                    ?></div>
                                                       
                                                    </li>
                                                        
                                                                                            <div class="panel-group accordion" id="accordions" style="margin: 0px 0px 0px 0px !important">

                                       
                                    </div> <?php
                                    
                                    
                                    
                                    if ($respondida) {
                                        ?>
                                    
                                            <div class="panel panel-default">
                                                        <div class="panel-heading">
                                                            <h4 class="panel-title">
                                                                <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="<?php echo '#collapsed'.$collapsed; ?>" aria-expanded="false">
                                                                    Resposta
                                                                </a>
                                                            </h4>
                                                        </div>
                                                        <div id="<?php echo 'collapsed'.$collapsed; ?>" class="panel-collapse collapse" aria-expanded="false">
                                                            <div class="panel-body border-palegreen">
                                                                <?php echo $pergunta['ST_RESPOSTA_PER']; ?>
                                                            </div>
                                                        </div>
                                                    </div>  
                                                   <?php 
                                                   
                                    }
                                    $collapsed++;
                                                    
                                                    
                                                                }         
                                                            } }else {
                                                                $elemento = new Elementoshtml_Alerts();
                                                                echo $elemento->warning("Nao tem perguntas.");
                                                            }
                                                            ?>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>

                                </div>
                            </div>

<script type="text/javascript">
    
    function porcentagem(valor1, valor2) {
        if (valor1 == 0 || valor2 == 0) {
            return 0;
        } else {
            return parseInt((valor1*100)/valor2);
        }
    }
    
    function quadrados(actual) {
        var default_ = 'quadclass badge badge-default badge-square';
        
        $('.quadclass').removeClass().addClass(default_);      
        $('#quad_'+actual).removeClass('badge-default').addClass('badge-primary');
    }
    
    function exercicios() {
       
        $('#btnRespostas').bind('click', function() {
            var curso = $('#curso').val();
            var slide = $('#slide').val();
            $.post('respostas', {slide: slide, curso: curso}, function(dados) {
                var respostas = dados.respostas[0].ST_RESPOSTAS_USC;
                var verdadeiras = dados.verdadeiras[0].ST_RESPOSTAS_SLI;
                var valores_verdadeiras = JSON.parse(verdadeiras);
                var valores_respostas = JSON.parse(respostas);
                var perguntas = 0;
                var corretas = 0;
                
                $.each(valores_verdadeiras, function(key, value) { 
                    perguntas = perguntas + 1;
                    $.each(valores_respostas, function(key2, value2) {
                        
                        if (key == key2) {
                            var selector = '';
                            var selector_out = '';
                            if (value == value2) {
                                selector = '#'+key+'_check'; 
                                selector_out = '#'+key+'_times';
                                corretas = corretas + 1;
                                $('#respCorreta_'+key).html('');
                            } else {
                                selector = '#'+key+'_times';
                                selector_out = '#'+key+'_check';
                                $('#respCorreta_'+key).html(value);
                            }
                            $(selector).attr('style','');
                            $(selector_out).attr('style','display:none');
                            $('#'+key).val(value2);
                                                            
                        }
                    });
                });   
                var c = parseInt($('#vlCorretas').html()) + corretas;
                var p = parseInt($('#vlExercicios').html())+perguntas;
                $('#vlCorretas').html(c);
                $('#vlExercicios').html(p);
                $('#vlPorcentagemExercicios').html(porcentagem(c,p)+'%');
                
            });
        });
        
        $('#btnCorregir').bind('click', function() {
            var curso = $('#curso').val();
            var slide = $('#slide').val();
     
            var arr = {};
            
            $.post("respostas", {slide: slide, curso: curso}, function(dados) {
                var resp = dados.verdadeiras[0].ST_RESPOSTAS_SLI;
                var valores = JSON.parse(resp);
                
                $.each(valores, function(key, value) {
                    var selector = '#'+key;
                    arr[key] = $(selector).val();
                });
                var jsonarr = JSON.stringify(arr);
                $.post("enviarrespostas", {ST_RESPOSTAS_USC: jsonarr, ID_SLIDE_USC: slide, ID_CURSO_USC: curso }, function(response) {
                    $('#btnRespostas').trigger('click');
                });
            });
            
        });
    }
    
    function verificarRespostas() {
        var respostas = $('#respostas').val();
        
        if (respostas !== '') {
            var verdadeiras = $('#verdadeiras').val();
            var valores_verdadeiras = JSON.parse(verdadeiras);
            
            var valores_respostas = JSON.parse(respostas);
            var perguntas = 0;
            var corretas = 0;

            $.each(valores_verdadeiras, function(key, value) { 
                perguntas = perguntas + 1;
                $.each(valores_respostas, function(key2, value2) {

                    if (key == key2) {
                        var selector = '';
                        var selector_out = '';
                        if (value == value2) {
                            selector = '#'+key+'_check'; 
                            selector_out = '#'+key+'_times';
                            corretas = corretas + 1;
                            $('#respCorreta_'+key).html('');
                        } else {
                            selector = '#'+key+'_times';
                            selector_out = '#'+key+'_check';
                            $('#respCorreta_'+key).html(value);
                        }
                        $(selector).attr('style','');
                        $(selector_out).attr('style','display:none');
                        $('#'+key).val(value2);

                    }
                });
            });   
//            $('#vlCorretas').html(parseInt($('#vlCorretas').html())+corretas);
//            $('#vlExercicios').html(parseInt($('#vlExercicios').html())+perguntas);    
            $('#btnCorregir').css("display","none");
            $('#btnRespostas').css("display","none");            
        }
    };
    
    function recalcular_quadrados(actual) {
        $('#divQuadrantes').html('');
        var quantidade = $('#quantidade').val();
        var quadrados_quantidade = quantidade;
        var i = 1;

        if (quadrados_quantidade > 14) {
            quadrados_quantidade = 14;
        }

        if (actual >= 8) {
            var aux = actual + 8;
            if (aux < quantidade) {
                i = actual - 7;
                quadrados_quantidade = actual + 8;
            } else {
                quadrados_quantidade = quantidade;
                i = quantidade - 14;
            }
        }

        var html = '<center>';
        var classe = '';
        for (i; i <= quadrados_quantidade; i++) {
            classe = 'default';
            if (i == actual) {
                classe = 'primary';
            }
            html += '<a href="javascript:void(0)" class="quadslide" data-slide="'+i+'"><span id="quad_'+i+'" class="badge badge-'+classe+' badge-square" style="margin-right: 7px; margin-right: 7px;">'+i+'</span></a>';
        }
        html += '</center>';
        $('#divQuadrantes').html(html);
        
        quadslideEvent();
    }
    
    function quadslideEvent() {
        $('.quadslide').bind('click', function() {
            var slide = $(this).data('slide');
            $('#slide').val(slide - 1);
            $('#sig').trigger('click');
        });    
    }
    
    $(function() {
      
        verificarRespostas();
        exercicios();
        
        quadslideEvent();
        
        $('.btnExcluir').bind('click', function() {
            var pergunta = $(this).attr('valor'); 
            var excluir_pergunta = confirm('Deseja excluir a pergunta?');
            if (excluir_pergunta) {
                $.post("../perguntas/excluirpergunta", {ID_PERGUNTA_PER: pergunta}, function(dados) {
                   window.location.reload();
                });
            }
        });
        
        $('#Gravar').bind('click',function() {
            var curso = $('#curso').val();
            var anotacoes = $('#ST_TEXTO_ANO').val();
            var usuario = 1;
            
            $.post("gravaranotacoes", {ID_CURSO_CR : curso, ID_USUARIO_USU: usuario, ST_TEXTO_ANO: anotacoes}, function(data) {
                $('#tituloForm').html('Anotacoes <span style="width: 6px">&nbsp;&nbsp;&nbsp; utima modificao: '+ data +' </span>');
            });
        });
        
        $('#fim').bind('click', function() {     
            var curso = $('#curso').val();
            var slide = parseInt($('#quantidade').val());
            
            $.post("vercursojson", {curso : curso, slide: slide}, function(data) {
                    var resposta = data.ST_RESPOSTAS_USC;
                    if (resposta !== '') {
                        resposta = data.ST_RESPOSTAS_USC[0].ST_RESPOSTAS_USC;
                    }
                    
                    quadrados(slide);
                    
                    $('#htmlslide').html(data[0].ST_SLIDE_SLI);
                    $('#numeroslide').html(data[0].NM_SLIDE_SLI);
                    $('#tituloslide').html(data[0].ST_TITULO_SLI);
                    $('#verdadeiras').html(data[0].ST_RESPOSTAS_SLI);
                    $('#respostas').val(resposta);
                    $('#slide').val(slide);
                    verificarRespostas();
                    exercicios();
                    recalcular_quadrados(slide);
            });
        });
        
        
        $('#sig').bind('click', function() {     
            
            var curso = $('#curso').val();
            var slide = parseInt($('#slide').val())+1;
            
            if (slide <= $('#quadrados_quantidade').val()) {
            
                $.post("vercursojson", {curso : curso, slide: slide}, function(data) {
                        var resposta = data.ST_RESPOSTAS_USC;
                        if (resposta !== '') {
                            resposta = data.ST_RESPOSTAS_USC[0].ST_RESPOSTAS_USC;
                        }

                        quadrados(slide);

                        $('#htmlslide').html(data[0].ST_SLIDE_SLI);
                        $('#numeroslide').html(data[0].NM_SLIDE_SLI);
                        $('#tituloslide').html(data[0].ST_TITULO_SLI);
                        $('#verdadeiras').val(data[0].ST_RESPOSTAS_SLI);
                        $('#respostas').val(resposta);
                        $('#slide').val(slide);
                        verificarRespostas();
                        exercicios();
                        recalcular_quadrados(slide);
                });
            }
        });
        
        $('#ant').bind('click', function() {     
            var curso = $('#curso').val();
            var slide = parseInt($('#slide').val())-1;
            
            if (slide > 0) {
            
                $.post("vercursojson", {curso : curso, slide: slide}, function(data) {
                        var resposta = data.ST_RESPOSTAS_USC;
                        if (resposta !== '') {
                            resposta = data.ST_RESPOSTAS_USC[0].ST_RESPOSTAS_USC;
                        }
                        quadrados(slide);

                        $('#htmlslide').html(data[0].ST_SLIDE_SLI);   
                        $('#numeroslide').html(data[0].NM_SLIDE_SLI);
                        $('#tituloslide').html(data[0].ST_TITULO_SLI);
                        $('#slide').val(slide);
                        $('#verdadeiras').val(data[0].ST_RESPOSTAS_SLI);
                        $('#respostas').val(resposta);
                        verificarRespostas();
                        exercicios();
                        recalcular_quadrados(slide);
                });
            }
        });   
        $('#inicio').bind('click', function() {     
            var curso = $('#curso').val();
            var slide = 1;
            
            $.post("vercursojson", {curso : curso, slide: slide}, function(data) {
                    var resposta = data.ST_RESPOSTAS_USC;
                    if (resposta !== '') {
                        resposta = data.ST_RESPOSTAS_USC[0].ST_RESPOSTAS_USC;
                    }
                    quadrados(slide);
                    
                    $('#htmlslide').html(data[0].ST_SLIDE_SLI);   
                    $('#numeroslide').html(data[0].NM_SLIDE_SLI);
                    $('#tituloslide').html(data[0].ST_TITULO_SLI);
                    $('#slide').val(slide);
                    $('#verdadeiras').html(data[0].ST_RESPOSTAS_SLI);
                    $('#respostas').val(resposta);
                    verificarRespostas();
                    exercicios();
                    recalcular_quadrados(slide);
            });
        });   
    });
    
    $(document).keydown(function(e) {
        switch(e.which) {
            case 37:
                $('#ant').trigger('click');// left
            break;

            case 39: // right
                $('#sig').trigger('click')
            break;

            default: return; // exit this handler for other keys
    }
    e.preventDefault(); // prevent the default action (scroll / move caret)
});
    
</script>    

