<?php
   $cursos = $this->cursos;
   $perguntas = $this->perguntas;
   $pergunta = $perguntas[0];
   
  $cantCursos = $this->cantCursos;
  $cantCursos = $cantCursos[0];
?>

<!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                                    <div class="databox bg-white radius-bordered">
                                        <div class="databox-left no-padding">
                                            <img src="assets/img/avatars/John-Smith.jpg" style="width:65px; height:65px;">
                                        </div>
                                        <div class="databox-right padding-top-20">
                                            <div class="databox-stat palegreen">
                                                <i class="stat-icon icon-xlg fa fa-phone"></i>
                                            </div>
                                            <div class="databox-text darkgray">JOHN SMITH</div>
                                            <div class="databox-text darkgray">TOP RESELLER</div>
                                        </div>
                                    </div>
                                </div>-->
<div class="row">
<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <div class="orders-container">
                                <div class="orders-header">
                                    <h6>Cursos de exercìcios</h6>
                                </div>
                                <ul class="orders-list">
                                    <?php
                                     foreach ($cursos as $curso) {
                                         ?>
                                         
                                     <li class="order-item">
                                        <div class="row">
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker"><a href="<?php echo $this->baseUrl().'/curso/ficha?curso='.$curso['ID_ID_CR']; ?>"><?php echo $curso['ST_NOME_CR']; ?></a></div>
                                                <div class="item-time">
                                                    <i class="fa fa-calendar"></i>
                                                    <span><?php echo '&nbsp;&nbsp;  '.$curso['Quantidade']." slides"; ?></span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <span class="currency">R$</span>
                                                    <span class="price"><?php echo $curso['VL_CUSTO_CR']; ?></span>
                                                </div>
                                            </div>
                                        </div>
                                         <a class="item-more" id="lnk" href="javascript:void(0);" class="btn btn-default" data-container="body" data-titleclass="bordered-purple" data-class="dark" data-toggle="popover-hover" data-placement="left" data-title="Hover" data-content="Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum.." data-original-title="" title="">
                                                     <i></i>
                                                </a>

                                    </li>
                                    
                                    <div class="popover fade right in" id="popover84932" style="width: 276px; top: 25px; left: 250px; display: none;">
                                        <div class="arrow" style="top: 50%;"></div>
                                            <h3 class="popover-title bordered-blueberry">Descricao</h3>
                                        <div class="popover-content"><?php echo $curso['ST_DESCR_CR']; ?></div>
                                    </div>
                                    
                                    
                                    
                                    
                                   <?php  }
                                    
                                    ?>
                                    
                                    
                                   
                                
                                </ul>
<!--                                <div class="orders-footer">
                                    <a class="show-all" href=""><i class="fa fa-angle-down"></i> Show All</a>
                                    <div class="help">
                                        <a href=""><i class="fa fa-question"></i></a>
                                    </div>
                                </div>-->
                            </div>
                        </div>

<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-orange" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-book"></i>
                                            </div>
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number orange"><?php echo $cantCursos['cursos']; ?></span>
                                            <div class="databox-text darkgray"><a href="<?php echo $this->baseUrl().'/curso/cursos'; ?>">CURSOS</a></div>
                                            <div class="databox-stat orange radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
   
     <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-yellow" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-user"></i>
                                            </div> 
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number yellow"></span>
                                            <div class="databox-text darkgray"><a href="<?php echo $this->baseUrl().'/usuario/index'; ?>">MINHA CONTA</a></div>
                                            <div class="databox-stat yellow radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
    
<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-azure" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-question"></i>
                                            </div>
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number azure"><?php echo $pergunta['perguntas']; ?></span>
                                            <div class="databox-text darkgray">MINHAS PERGUNTAS</div>
                                            <div class="databox-stat azure radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>

   

</div>




<script type="text/javascript">
    $(function() {
       $('#lnk').bind('mouseover', function(){
           $('#popover84932').show();
       });
  
       $('#lnk').bind('mouseout', function(){
           $('#popover84932').hide();
       });  
    }); 

</script>