<?php
   $cursos = $this->cursos;
   $perguntas = $this->perguntas;
   if (!empty($perguntas)) {
    $pergunta = $perguntas[0];
   } else {
    $pergunta = 0;   
   }
   
  $cantCursos = $this->cantCursos;
  $cantCursos = $cantCursos[0];
?>
<!--<a href="javascript:void(0);" class="btn btn-default  btn-circle btn-lg"><i class="glyphicon glyphicon-pencil"></i></a>-->
<!--<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                                    <div class="databox bg-white radius-bordered">
                                        <div class="databox-left no-padding">
                                            <img src="assets/img/avatars/John-Smith.jpg" style="width:65px; height:65px;">
                                        </div>
                                        <div class="databox-right padding-top-20">
                                            <div class="databox-stat palegreen">
                                                <i class="stat-icon icon-xlg fa fa-phone"></i>
                                            </div>
                                            <div class="databox-text darkgray">JOHN SMITH</div>
                                            <div class="databox-text darkgray">TOP RESELLER</div>
                                        </div>
                                    </div>
                                </div>-->
<div class="row">
<!--<div class="col-lg-3 col-md-3 col-sm-12 col-xs-12">
                            <div class="orders-container">
                                <div class="orders-header">
                                    <h6>Cursos</h6>
                                </div>
                                <ul class="orders-list">
                                    <?php
                                    $indice = 0;
                                     foreach ($cursos as $curso) {
                                         $indice++;
                                         ?>
                                    
                                     <li class="order-item">
                                        <div class="row">
                                            
                                            <div class="col-lg-8 col-md-8 col-sm-8 col-xs-8 item-left">
                                                <div class="item-booker"><a href="<?php echo $this->baseUrl().'/curso/ficha?curso='.$curso['ID_ID_CR']; ?>"><?php echo $curso['ST_NOME_CR']; ?></a></div>
                                                <div class="item-time">
                                                    
                                                    <a title="Fazer" class="" style="margin-right:5px" href="<?php echo $this->baseUrl().'/curso/vercurso?curso='.$curso['ID_ID_CR'].'&slide=1'; ?>"><i class="glyphicon glyphicon-pencil circular"></i></a>
                                                    <i class="fa fa-calendar"></i>
                                                    <span><?php echo '&nbsp;&nbsp;  '.$curso['Quantidade']." slides"; ?></span>
                                                </div>
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 item-right">
                                                <div class="item-price">
                                                    <?php 
                                                        $currency = $curso['VL_CUSTO_CR'] > 0 ? 'R$' : ''; 
                                                    ?>
                                                    <span class="currency"><?php echo $currency; ?></span>
                                                    <span class="price"><?php if ($curso['VL_CUSTO_CR'] > 0) { echo $curso['VL_CUSTO_CR'];} else { echo '<span style="color: green"><b>GRATIS</b></span>'; }?></span>
                                                </div>
                                            </div>
                                        </div>
                                         <a class="item-more lnk" id="lnk" href="javascript:void(0);" class="btn btn-default" data-container="body" data-titleclass="bordered-purple" data-class="dark" data-toggle="popover-hover" data-placement="left" data-title="Hover" data-content="<?php echo $curso['ST_MINIDESCR_CR']; ?>" data-indice="<?php echo $indice; ?>" data-original-title="" title="">
                                                     <i></i>
                                                </a>

                                    </li>
                                    
                                    <div class="popover fade right in" id="popover84932" style="width: 276px; top: 0px; left: 250px; height:200px; display: none;">
                                        <div class="arrow" style="top: 50%;"></div>
                                            <h3 class="popover-title bordered-blueberry">Descricao</h3>
                                        <div class="popover-content" id="popover"></div>
                                    </div>
                                    
                                    
                                    
                                    
                                   <?php  }
                                    
                                    ?>
                                    
                                    
                                   
                                
                                </ul>
                                <div class="orders-footer">
                                    <a class="show-all" href=""><i class="fa fa-angle-down"></i> Show All</a>
                                    <div class="help">
                                        <a href=""><i class="fa fa-question"></i></a>
                                    </div>
                                </div>
                            </div>
                        </div>-->

<div class="col-lg-2 col-sm-4 col-xs-6">
    <a href="<?php echo $this->baseUrl().'/curso/novo' ?>" > 
                                    <div class="databox databox-lg databox-vertical databox-inverted bg-white databox-shadowed">
                                        <div class="databox-top">
                                            <div class="databox-piechart">
                                                <div data-toggle="easypiechart" class="easyPieChart block-center" data-barcolor="#e75b8d" data-linecap="butt" data-percent="40" data-animate="500" data-linewidth="8" data-size="100" data-trackcolor="#eee" style="width: 100px; height: 100px; line-height: 100px;">
                                                    <span class="white font-200"><i class="fa fa-file green" style="font-size:100px"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="databox-bottom no-padding text-align-center">
                                            <span class="databox-number lightcarbon no-margin">&nbsp;</span>
                                            <span class="databox-text lightcarbon no-margin">CADASTRAR CURSO</span>
                                        </div>
                                    </div>
    </a>
                                </div>

<div class="col-lg-2 col-sm-4 col-xs-6">
        <a href="<?php echo $this->baseUrl().'/curso/cursos' ?>" > 
                                    <div class="databox databox-lg databox-vertical databox-inverted bg-white databox-shadowed">
                                        <div class="databox-top">
                                            <div class="databox-piechart">
                                                <div data-toggle="easypiechart" class="easyPieChart block-center" data-barcolor="#e75b8d" data-linecap="butt" data-percent="40" data-animate="500" data-linewidth="8" data-size="100" data-trackcolor="#eee" style="width: 100px; height: 100px; line-height: 100px;">
                                                    <span class="white font-200"><i class="fa fa-book pink" style="font-size:100px"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="databox-bottom no-padding text-align-center">
                                            <span class="databox-number lightcarbon no-margin">&nbsp;</span>
                                            <span class="databox-text lightcarbon no-margin">CURSOS</span>
                                        </div>
                                    </div>
        </a>
                                </div>

<div class="col-lg-2 col-sm-4 col-xs-6">
    <a href="<?php echo $this->baseUrl().'/usuario/index' ?>" > 
                                    <div class="databox databox-lg databox-vertical databox-inverted bg-white databox-shadowed">
                                        <div class="databox-top">
                                            <div class="databox-piechart">
                                                <div data-toggle="easypiechart" class="easyPieChart block-center" data-barcolor="#e75b8d" data-linecap="butt" data-percent="40" data-animate="500" data-linewidth="8" data-size="100" data-trackcolor="#eee" style="width: 100px; height: 100px; line-height: 100px;">
                                                    <span class="white font-200"><i class="fa fa-user yellow" style="font-size:100px"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="databox-bottom no-padding text-align-center">
                                            <span class="databox-number lightcarbon no-margin">&nbsp;</span>
                                            <span class="databox-text lightcarbon no-margin">CONTA</span>
                                        </div>
                                    </div>
    </a>
                                </div>

<div class="col-lg-2 col-sm-4 col-xs-6">
    <a href="<?php echo $this->baseUrl().'/perguntas/index' ?>" > 
                                    <div class="databox databox-lg databox-vertical databox-inverted bg-white databox-shadowed">
                                        <div class="databox-top">
                                            <div class="databox-piechart">
                                                <div data-toggle="easypiechart" class="easyPieChart block-center" data-barcolor="#e75b8d" data-linecap="butt" data-percent="40" data-animate="500" data-linewidth="8" data-size="100" data-trackcolor="#eee" style="width: 100px; height: 100px; line-height: 100px;">
                                                    <span class="white font-200"><i class="fa fa-question azure" style="font-size:100px"></i></span>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="databox-bottom no-padding text-align-center">
                                            <span class="databox-number lightcarbon no-margin">&nbsp;</span>
                                            <span class="databox-text lightcarbon no-margin">PERGUNTAS</span>
                                        </div>
                                    </div> 
    </a>
                                </div>
<!--<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-green" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-file"></i>
                                            </div>
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number green">&nbsp;</span>
                                            <div class="databox-text darkgray"><a href="<?php echo $this->baseUrl().'/curso/novo'; ?>">ADICIONE SEU CURSO</a></div>
                                            <div class="databox-stat green radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->

<!--<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-orange" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-book"></i>
                                            </div>
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number orange">&nbsp;<?php echo $cantCursos['cursos']; ?></span>
                                            <div class="databox-text darkgray"><a href="<?php echo $this->baseUrl().'/curso/cursos'; ?>"><?php echo utf8_encode('CURSOS DISPONÍVEIS'); ?></a></div>
                                            <div class="databox-stat orange radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->
   
<!--     <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-yellow" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-user"></i>
                                            </div> 
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number yellow">&nbsp;</span>
                                            <div class="databox-text darkgray"><a href="<?php echo $this->baseUrl().'/usuario/index'; ?>">MINHA CONTA</a></div>
                                            <div class="databox-stat yellow radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->
    
<!--<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                    <div class="databox radius-bordered databox-shadowed databox-graded" style="height:100px !important">
                                        <div class="databox-left bg-azure" style="weight:100px !important; height:100px !important;">
                                            <div class="databox-icon">
                                                <i class="fa fa-question"></i>
                                            </div>
                                        </div>
                                        <div class="databox-right">
                                            <span class="databox-number azure"><?php echo $pergunta['perguntas'] ? $pergunta['perguntas'] : 0; ?></span>
                                            <div class="databox-text darkgray"><a href="<?php echo $this->baseUrl().'/perguntas/index' ?>">MINHAS PERGUNTAS</a></div>
                                            <div class="databox-stat azure radius-bordered">
                                                <i class="stat-icon icon-lg fa fa-tasks"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>-->

   

</div>




<script type="text/javascript">
    $(function() {
       $('.lnk').bind('mouseover', function(){
           var indice = $(this).data('indice');
           var loc = -22;
           var mais = (indice-1)*70;

           $('#popover84932').css('top', ((loc)+mais)+'px');         
           $('#popover').html($(this).data('content'));
           $('#popover84932').show();
       });
  
       $('.lnk').bind('mouseout', function(){
           $('#popover84932').hide();
       });  
    }); 

</script>