   <meta name="description" content="data tables">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon">
    
    <?php print_r($this->baseUrl('assets/css/weather-icons.min.css')); die('.'); ?>
    
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/dataTables.bootstrap.css'))?>    
        <a href="_head.php"></a>
    <?php $this->headScript()->appendFile($this->baseUrl('assets/js/jquery-2.0.3.min.js')) ?>
        
        Page Related Scripts 
    <?php $this->headScript()->appendFile($this->baseUrl('assets/js/toastr/toastr.js')) ?>

    <?php $this->headScript()->appendFile($this->baseUrl('assets/js/bootstrap.min.js')) ?>
    <?php $this->headScript()->appendFile($this->baseUrl('assets/js/slimscroll/jquery.slimscroll.min.js')) ?>
        
    Beyond Scripts
    <?php $this->headScript()->appendFile($this->baseUrl('assets/js/beyond.min.js')) ?>     
        
    Basic Styles
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/bootstrap.min.css'))?>
    
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link id="bootstrap-rtl-link" href="" rel="stylesheet">
        
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/font-awesome.css'))?>           
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/weather-icons.min.css'))?>           
    
    <link href="assets/css/font-awesome.min.css" rel="stylesheet"> 

    Fonts
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">
    
   Page Related styles
   <link href="assets/css/dataTables.bootstrap.css" rel="stylesheet">
   
    Beyond styles
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/beyond.min.css'))?>   
    <link id="beyond-link" href="assets/css/beyond.min.css" rel="stylesheet">
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/demo.min.css'))?> 
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/typicons.min.css'))?> 
    <?php $this->headLink()->appendStylesheet($this->baseUrl('assets/css/animate.min.css'))?> 
    <link href="assets/css/demo.min.css" rel="stylesheet">
    <link href="assets/css/typicons.min.css" rel="stylesheet">
    <link href="assets/css/animate.min.css" rel="stylesheet">
    <link id="skin-link" href="" rel="stylesheet" type="text/css">

    Skin Script: Place this script in head to load scripts for skins and rtl support
    <script async="" src="http://www.google-analytics.com/analytics.js"></script>
    
    <?php $this->headScript()->appendFile($this->baseUrl('assets/js/skins.min.js')) ?>
        
    <?php echo $this->headLink()?>     
    <?php echo $this->headScript()?>  
    
</head>
Head Ends
Body
<body>
    <div class="login-container animated fadeInDown">
        <div class="loginbox bg-white">
            <div class="loginbox-title">LOG IN</div>
            <div class="loginbox-social">
                <div class="social-title ">Connect with Your Social Accounts</div>
                <div class="social-buttons">
                    <a href="" class="button-facebook">
                        <i class="social-icon fa fa-facebook"></i>
                    </a>
                    <a href="" class="button-twitter">
                        <i class="social-icon fa fa-twitter"></i>
                    </a>
                    <a href="" class="button-google">
                        <i class="social-icon fa fa-google-plus"></i>
                    </a>
                </div>
            </div>
           <form action="/bobby/public/login/logon" method="post">
            <div class="loginbox-or">
                <div class="or-line"></div>
            </div>
            <div class="loginbox-textbox">
                <input type="text" class="form-control" name="ST_LOGIN_USU" placeholder="Email">
            </div>
            <div class="loginbox-textbox">
                <input type="text" class="form-control" name="ST_SENHA_USU" placeholder="Senha">
            </div>
            <div class="loginbox-forgot">
                <a href="">Esqueceu a senha?</a>
            </div>
            <div class="loginbox-submit">
                <input type="submit" class="btn btn-primary btn-block" name="BTN_LOGAR" value="Logar">
            </div>
            <div class="loginbox-signup">
                <a href="register.html">Cadastra-se</a>
            </div>
            </form>
        </div>
        <div class="logobox">
        </div>
    </div>

    Basic Scripts
    <script src="assets/js/jquery-2.0.3.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/slimscroll/jquery.slimscroll.min.js"></script>

    Beyond Scripts
    <script src="assets/js/beyond.js"></script>

    Google Analytics::Demo Only
    <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'http://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-52103994-1', 'auto');
        ga('send', 'pageview');

    </script>

Body Ends

</body></html>
   
   