<?php

include APPLICATION_PATH.'/decorators/Form.php';
include APPLICATION_PATH.'/forms/slide/editar.php';

$slide = $this->slide;
$slide = $slide[0];

$decform = new Decorators_Form();
$form = new Forms_Slide_Editar(array('titulo' => 'Editar Slide'));
$form->addDecorator($decform);
$form->populate($slide);
echo $form;

?>

<div class="col-lg-6 col-sm-6 col-xs-12">
    <div class="well with-header"><?php echo $slide['ST_SLIDE_SLI']; ?></div>
    </div>