<?php

    $perguntas = $this->perguntas;
?>

<div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div class="widget">
                                <div class="widget-header  with-footer">
                                    <span class="widget-caption">Responsive Flip Scroll Tables</span>
                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="maximize">
                                            <i class="fa fa-expand"></i>
                                        </a>
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="widget-body">
                                    <div class="alert alert-info fade in alert-radius-bordered alert-shadowed">
                                        <button class="close" data-dismiss="alert">
                                            ×
                                        </button>
                                        <i class="fa-fw fa fa-info"></i>

                                        <strong>Flip Scroll Table:</strong> Flips between horizontal and vertical scrolls according to page width
                                    </div>
                                    <div class="flip-scroll">
                                        <table class="table table-bordered table-striped table-condensed flip-content">
                                            <thead class="flip-content bordered-palegreen">
                                                <tr>
                                                    <th>
                                                        Code
                                                    </th>
                                                    <th>
                                                        Company
                                                    </th>
                                                    <th class="numeric">
                                                        Price
                                                    </th>
                                                    <th class="numeric">
                                                        Change
                                                    </th>
                                                    <th class="numeric">
                                                        Change %
                                                    </th>
                                                    <th class="numeric">
                                                        Open
                                                    </th>
                                                    <th class="numeric">
                                                        High
                                                    </th>
                                                    <th class="numeric">
                                                        Low
                                                    </th>
                                                    <th class="numeric">
                                                        Volume
                                                    </th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                    foreach ($perguntas as $pergunta) {
                                                     
                                                        echo '<tr>
                                                    <td>
                                                        <a href="javascript:void(0)" id="ver" data-respostaid="'.$pergunta['ID_PERGUNTA_PER'].'">
                                                            <i class="fa fa-arrow-circle-o-right"></i>
                                                        </a> 
                                                        <input type="hidden" id="resposta_'.$pergunta['ID_PERGUNTA_PER'].'" data-valor="'.$pergunta['ST_RESPOSTA_PER'].'" />
                                                    </td>
                                                    <td>
                                                        '.$pergunta['ST_PERGUNTA_PER'].'
                                                    </td>
                                                    <td class="numeric">
                                                        $1.38
                                                    </td>
                                                    <td class="numeric">
                                                        -0.01
                                                    </td>
                                                    <td class="numeric">
                                                        -0.36%
                                                    </td>
                                                    <td class="numeric">
                                                        $1.39
                                                    </td>
                                                    <td class="numeric">
                                                        $1.39
                                                    </td>
                                                    <td class="numeric">
                                                        $1.38
                                                    </td>
                                                    <td class="numeric">
                                                        9,395
                                                    </td>
                                                </tr>';
                                                
                                                    }
                                                ?>
                                                
                                                <tr>
                                                    <td>
                                                        AAC
                                                    </td>
                                                    <td>
                                                        AUSTRALIAN AGRICULTURAL COMPANY LIMITED.
                                                    </td>
                                                    <td class="numeric">
                                                        $1.38
                                                    </td>
                                                    <td class="numeric">
                                                        -0.01
                                                    </td>
                                                    <td class="numeric">
                                                        -0.36%
                                                    </td>
                                                    <td class="numeric">
                                                        $1.39
                                                    </td>
                                                    <td class="numeric">
                                                        $1.39
                                                    </td>
                                                    <td class="numeric">
                                                        $1.38
                                                    </td>
                                                    <td class="numeric">
                                                        9,395
                                                    </td>
                                                </tr>
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
</div>
                    
              <?php
                include_once APPLICATION_PATH.'/forms/anotacoes.php';
                $form = new Forms_Anotacoes();
              
              ?>


<div id="formA" style="display: none">
    <div class="widget-body" style="width:600px; height: 500px">
        <div id="resposta_div"></div>      
    </div>
</div>

<?php echo $this->headScript()?> 
<script type="text/javascript">
   
   $(function() {
       $('#ver').bind('click', function() {
//           console.log($(this).val());
//           console.log($(this));
           var respostaid = $(this).data('respostaid');
           var resposta = $('#resposta_'+respostaid).data('valor');
           $('#resposta_div').html(resposta);
            $('#formA').dialog({
                    modal: true,
                        position: [400,80],
//                    buttons: {
//                        "Aceitar": function() {
//                            $(this).dialog("close");
//                        },
      //  },
//        close: function() {
//        }

            }); 
       });
   });
   
</script>                   