<?php

    $perguntas = $this->perguntas;
    
    if (count($perguntas) > 0) {
?>



<div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div class="widget">
                                <div class="widget-header  with-footer">
                                    <span class="widget-caption">Perguntas dos cursos</span>
<!--                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="maximize">
                                            <i class="fa fa-expand"></i>
                                        </a>
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>-->
                                </div>
                                <div class="widget-body">
<!--                                    <div class="alert alert-info fade in alert-radius-bordered alert-shadowed">
                                        <button class="close" data-dismiss="alert">
                                            ×
                                        </button>
                                        <i class="fa-fw fa fa-info"></i>

                                        <strong>Flip Scroll Table:</strong> Flips between horizontal and vertical scrolls according to page width
                                    </div>-->
                                    <div class="flip-scroll">
                                        <table class="table table-bordered table-striped table-condensed flip-content">
                                            <thead class="flip-content bordered-palegreen">
                                                <tr>
                                                    <th style="width: 5%">
                                                        
                                                    </th>
                                                    <th style="width: 15%">
                                                        Curso
                                                    </th>                                                    
                                                    <th>
                                                        Pergunta
                                                    </th>
                                               
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                    foreach ($perguntas as $pergunta) {
                                                     
                                                        echo '<tr>
                                                    <td>
                                                    <a href="javascript:void(0)" id="vder" data-respostaid="'.$pergunta['ID_PERGUNTA_PER'].'">
                                                            <i class="fa fa-times"></i>
                                                        </a> 
                                                        <a href="javascript:void(0)" id="ver" data-respostaid="'.$pergunta['ID_PERGUNTA_PER'].'">
                                                            <i class="fa fa-arrow-circle-o-right"></i>
                                                        </a> 
                                                        <input type="hidden" id="resposta_'.$pergunta['ID_PERGUNTA_PER'].'" data-valor="'.$pergunta['ST_RESPOSTA_PER'].'" />
                                                    </td>
                                                    <td>
                                                        '.$pergunta['ST_NOME_CR'].'
                                                    </td>
                                                    <td>
                                                        '.$pergunta['ST_PERGUNTA_PER'].'
                                                    </td>
                                                
                                                </tr>';
                                                
                                                    }
                                                ?>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
</div>
                    
              <?php
//                include_once APPLICATION_PATH.'/forms/anotacoes.php';
//                $form = new Forms_Anotacoes();
              
              ?>


<div id="formA" style="display: none">
    <div class="">
    <div class="col-lg-6 col-sm-6 col-xs-12" style="width:600px">
            <div class="widget" style="width:600px">
                
                <div class="widget-header bordered-bottom bordered-blue">
                    <div class="widget-buttons">
                                     
                                        <a href="#" data-toggle="collapse" style="">
<!--                                            <i class="fa fa-minus"></i>-->
                                        </a>
                        <a href="#" class="cssClose" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                    <span class="widget-caption" id="tituloForm">Resposta</span>
                </div>
                <div class="widget-body" style="width:600px !important; height:400px">
                    <div><form action="method=post" style=""><dt id="ID_PERGUNTA_PER-label">&nbsp;</dt>
    <dd id="ID_PERGUNTA_PER-element">
    <input type="hidden" name="ID_PERGUNTA_PER" value="" id="ID_PERGUNTA_PER"></dd><dt id="ST_RESPOSTA_PER-label">&nbsp;</dt>
    <dd id="ST_RESPOSTA_PER-element">
    </dd><dt id="Responder-label">&nbsp;</dt><dd id="Responder-element">        
        </div>      
    </div>
    </div>
    </div>
        </div>
    </div>
<?php echo $this->headScript();
        
    } else {
        include APPLICATION_PATH.'/Elementoshtml/Alerts.php';
        echo Elementoshtml_Alerts::warning("Nao tem perguntas respondidas.");
        
    }
?> 
<script type="text/javascript">
   
//   $(function() {
//    $( "#dialog" ).dialog({
//        	closeOnEscape: false, 
//	open: function(event, ui) { 
//		// Set opacity 
//		$(this).parent().css('opacity', 0.6); 
//		// Hide close button 
//		$(this).parent().children().children(".ui-dialog-titlebar-close").hide(); 
//		// Handle opacity 
//		$(this).parent().hover( function () { 
//			$(this).css('opacity', 0.9); 
//		}, function (event) { 
//			$(this).css('opacity', 0.6); 
//		}); 
//	} 
//        
//    });
//  });
   
   $(function() {
       $('.cssClose').bind('click', function() {
          $('#formA').css('display','none'); 
       });
       
       
       $('#ver').bind('click', function() {
           
           var respostaid = $(this).data('respostaid');
           var resposta = $('#resposta_'+respostaid).data('valor');
           $.post('lida',{ID_PERGUNTA_PER:respostaid});
          $('#ST_RESPOSTA_PER-label').html(resposta);
           $('#formA').css('display',''); 
            $('#formA').dialog({
               position: [400,80],
               
            });
            
             $(".ui-dialog-titlebar-close").css('display','none');
       });
   });
   
</script>                   