<?php

    $perguntas = $this->perguntas;
    
    if (count($perguntas) > 0) {
?>



<div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div class="widget">
                                <div class="widget-header  with-footer">
                                    <span class="widget-caption">Perguntas dos cursos</span>
                                </div>
                                <div class="widget-body">
                                    <div class="flip-scroll">
                                        <table class="table table-bordered table-striped table-condensed flip-content">
                                            <thead class="flip-content bordered-palegreen">
                                                <tr>
                                                    <th style="width: 7%">
                                                        
                                                    </th>
                                                    <th style="width: 15%">
                                                        Curso
                                                    </th>                                                    
                                                    <th>
                                                        Pergunta
                                                    </th>
                                               
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <?php
                                                    foreach ($perguntas as $pergunta) { 
                                                        $check = '';
                                                        if (!empty($pergunta['ST_RESPOSTA_PER'])) {
                                                            $check = '<i class="fa fa-check green"></i>';
                                                        }
                                                        echo '<tr>
                                                    <td>
                                                        <a href="javascript:void(0)" class="excluir" data-respostaid="'.$pergunta['ID_PERGUNTA_PER'].'">
                                                            <i class="fa fa-times red"></i>
                                                        </a> 
                                                        <a href="javascript:void(0)" class="ver" id="ver" data-respostaid="'.$pergunta['ID_PERGUNTA_PER'].'">
                                                            <i class="fa fa-arrow-circle-o-right"></i>
                                                        </a> 
                                                        '.$check.'
                                                        <input type="hidden" id="resposta_'.$pergunta['ID_PERGUNTA_PER'].'" data-valor="'.$pergunta['ST_RESPOSTA_PER'].'" />
                                                    </td>
                                                    <td>
                                                        <a href="'.$this->baseUrl().'/curso/vercurso?slide=1&curso='.$pergunta['ID_CURSO_CR'].'">'.$pergunta['ST_NOME_CR'].'</a>
                                                    </td>
                                                    <td>
                                                        '.$pergunta['ST_PERGUNTA_PER'].'
                                                    </td>
                                                
                                                </tr>';
                                                
                                                    }
                                                ?>
                                                
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
</div>

<div id="formA" style="display: none">
    <div class="">
    <div class="col-lg-6 col-sm-6 col-xs-12" style="width:600px">
            <div class="widget" style="width:600px">
                
                <div class="widget-header bordered-bottom bordered-blue">
                    <div class="widget-buttons">
                                     
                                        <a href="#" data-toggle="collapse" style="">
<!--                                            <i class="fa fa-minus"></i>-->
                                        </a>
                        <a href="#" class="cssClose" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                    <span class="widget-caption" id="tituloForm">Resposta</span>
                </div>
                <div class="widget-body" style="width:600px !important; height:400px">
                    <div><form action="method=post" style=""><dt id="ID_PERGUNTA_PER-label">&nbsp;</dt>
    <dd id="ID_PERGUNTA_PER-element">
    <input type="hidden" name="ID_PERGUNTA_PER" value="" id="ID_PERGUNTA_PER"></dd><dt id="ST_RESPOSTA_PER-label">&nbsp;</dt>
    <dd id="ST_RESPOSTA_PER-element">
    </dd><dt id="Responder-label">&nbsp;</dt><dd id="Responder-element">        
        </div>      
    </div>
    </div>
    </div>
        </div>
    </div>
<?php echo $this->headScript();
        
    } else {
        include APPLICATION_PATH.'/Elementoshtml/Alerts.php';
        echo Elementoshtml_Alerts::warning("Nao tem perguntas respondidas.");
        
    }
?> 
<script type="text/javascript">

   $(function() {
        $('.excluir').bind('click', function() {
            var pergunta = $(this).data('respostaid'); 
            var excluir_pergunta = confirm('Deseja excluir a pergunta?');
            if (excluir_pergunta) {
                $.post("../perguntas/excluirpergunta", {ID_PERGUNTA_PER: pergunta}, function(dados) {
                     // console.log(dados);
                   window.location.reload();
                });
            }
        });
       
       
       $('.cssClose').bind('click', function() {
          $('#formA').css('display','none'); 
       });
       
       
       $('.ver').bind('click', function() {
           
           var respostaid = $(this).data('respostaid');
           var resposta = $('#resposta_'+respostaid).data('valor');
           $.post('lida',{ID_PERGUNTA_PER:respostaid});
          $('#ST_RESPOSTA_PER-label').html(resposta);
           $('#formA').css('display',''); 
            $('#formA').dialog({
               position: [400,80],
               
            });
            
             $(".ui-dialog-titlebar-close").css('display','none');
       });
   });
   
</script>                   