<?php

    $storage = new Zend_Auth_Storage_Session();
    $data = get_object_vars($storage->read());
    if (empty($data['NM_CREDITO_USU'])) {
        $data['NM_CREDITO_USU'] = '0.00';
    }
    $credito_ = number_format($data['NM_CREDITO_USU'],2,',','.');
    $cursos = $this->cursos;
    $credito = $this->creditos;
    if(count($data['NM_CREDITO_USU'])>0){
         $credito[0]['VL_VALOR_CREDITO'] = number_format($credito[0]['VL_VALOR_CREDITO'],2,',','.');
    }else{
         $credito[0]['VL_VALOR_CREDITO']='0,00';
    }

    $cantidad = count($cursos);
    
    $perguntas = $this->perguntas;
    $cantPerguntas = count($perguntas);
?>
<!--
<form action="<?php echo $this->baseUrl().'/usuario/perfil'; ?>" method="post" enctype="multipart/form-data" style="display: none">
    <input type="file" name="imgPerfil" id="imgPerfil" />
    <input type="submit" id="btnPerfil" name="btnPerfil" />
</form>-->
<?php
    include_once APPLICATION_PATH.'/Forms/FotoPerfil.php';
    $formPerfil = new Forms_FotoPerfil();
    echo $formPerfil;
    
    $file = APPLICATION_PATH."/../public/img/perfil/".$data['ST_USUARIO_USU'].'.jpg';
    
?>
<div class="row">
                        <div class="col-md-12">
                            <div class="profile-container">
                                <div class="profile-header row">
                                    <div class="col-lg-2 col-md-4 col-sm-12 text-center">
                                        <a href="javascript:void(0)" id="lnkPerfil"><img src="<?php 

                                            if (is_file($file)) {
                                                echo $this->baseUrl().'/img/perfil/'.$data['ST_USUARIO_USU'].'.jpg';
                                            } else {
                                                echo $this->baseUrl().'/img/perfil.jpg'; 
                                                
                                            }
                                        
                                        ?>" alt="" class="header-avatar"></a>
                                    </div>
                                    <div class="col-lg-4 col-md-4 col-sm-12 profile-info">
                                        <div class="header-fullname"><?php echo ucwords($data['ST_USUARIO_USU']); ?></div>
<!--                                        <a href="#" class="btn btn-palegreen btn-sm  btn-follow">
                                            <i class="fa fa-check"></i>
                                            Following
                                        </a>-->
                                        <div class="header-information">
                                            <?php echo $data['ST_EMAIL_USU']; ?>
                                        </div>
                                    </div>
                                    <div class="col-lg-5 col-md-12 col-sm-12 col-xs-12 profile-stats">
                                        <div class="row">
                                            <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12 stats-col">
                                                <div class="stats-value blue"><?php echo 'R$ '.$credito[0]['VL_VALOR_CREDITO'];  ?></div>
                                                <div class="stats-title">CREDITOS</div>
                                            </div>
                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 stats-col">
                                                <div class="stats-value pink"><?php echo $cantidad; ?></div>
                                                <div class="stats-title">
                                                <?php 
                                                    $stCurso = "CURSO";
                                                    if ($cantidad != 1) {
                                                        $stCurso .= 'S';
                                                    }
                                                    echo $stCurso;
                                                ?></div>
                                            </div>
                                            <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 stats-col">
                                                <div class="stats-value pink"><?php echo $cantPerguntas; ?></div>
                                                <div class="stats-title">
                                                    <?php
                                                    $stPergunta = "PERGUNTA";
                                                    if ($cantidad != 1) {
                                                        $stPergunta .= 'S';
                                                    }
                                                    echo '<a href="'.$this->baseUrl().'/perguntas/index">'.$stPergunta.'</a>';
                                                    ?></div>
                                            </div>
                                        </div>
                                        <div class="row">
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 inlinestats-col">
<!--                                                <i class="glyphicon glyphicon-map-marker"></i> Boston-->
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 inlinestats-col">
<!--                                                Rate: <strong>$250</strong>-->
                                            </div>
                                            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-4 inlinestats-col">
                                                <!--Age: <strong>24</strong>-->
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="profile-body">
                                    <div class="col-lg-12">
                                        <div class="tabbable">
                                            <ul class="nav nav-tabs tabs-flat  nav-justified" id="myTab11">
                                                <li class="">
                                                    
                                                    <a data-toggle="tab" href="#timeline" aria-expanded="false" id="lnkDados">
                                                        Dados pessoais
                                                    </a>
                                                </li>
                                                <li class="tab-red active">
                                                    <a data-toggle="tab" href="#overview" aria-expanded="true" id="lnkCursos">
                                                        Cursos
                                                    </a>
                                                </li>
                                                
                                                
                                            </ul>
                                            
                                        </div>
                                    </div>
                                </div>
                   
                            </div>
                        </div>
                    </div>
<br>

<div id="divCursos">
    <?php
    if ($cantidad > 0) {
$i = 0;
foreach($cursos as $curso) {
     if ($i == 3) {
         $i = 0;
         echo '</div><br>';
     }
    
    $curso['NM_UTIMAVIU_UC'] = !empty($curso['NM_UTIMAVIU_UC']) ? $curso['NM_UTIMAVIU_UC'] : 0;
    $porcentagem = $curso['cantidades'] == 0 ? 0 : ($curso['NM_UTIMAVIU_UC']*100)/$curso['cantidades'];
    if ($i == 0) {
        echo '<div class="row">';
    }
   
    ?>
<div class="col-lg-4 col-sm-6 col-xs-12">
                                                                    <div class="databox databox-xlg databox-halved databox-shadowed databox-vertical no-margin-bottom">
                                                                        <div class="databox-top bg-white padding-10">
                                                                            <div class="col-lg-4 col-sm-4 col-xs-4">
                                                                                <img src="<?php echo $this->baseUrl().'/../application/uploads/'.$curso['ST_IMAGEM_CR']; ?>" style="width:75px; height:75px;" class="image-circular bordered-3 bordered-palegreen">
                                                                            </div>
                                                                            <div class="col-lg-8 col-sm-8 col-xs-8 text-align-left padding-10">
                                                                                <span class="databox-header carbon no-margin"><?php echo $curso['ST_NOME_CR']; ?></span>
                                                                                <span class="databox-text lightcarbon no-margin"></span>
                                                                            </div>
                                                                        </div>
                                                                        <div class="databox-bottom bg-white no-padding">
                                                                            <div class="databox-row row-12">
                                                                                <div class="databox-row row-6 no-padding">
                                                                                    <div class="databox-cell cell-4 no-padding text-align-center bordered-right bordered-platinum">
                                                                                        <span class="databox-text sonic-silver  no-margin">Slides</span>
                                                                                        <span class="databox-number lightcarbon no-margin"><?php echo $curso['cantidades'] ?></span>
                                                                                    </div>
                                                                                    <div class="databox-cell cell-4 no-padding text-align-center bordered-right bordered-platinum">
                                                                                        <span class="databox-text sonic-silver no-margin">Lidas</span>
                                                                                        <span class="databox-number lightcarbon no-margin"><?php echo $curso['NM_UTIMAVIU_UC']; ?></span>
                                                                                    </div>
                                                                                    <div class="databox-cell cell-4 no-padding text-align-center">
                                                                                        <span class="databox-text sonic-silver no-margin">Porcentagem</span>
                                                                                        <span class="databox-number lightcarbon no-margin"><?php echo intval($porcentagem).'%'; ?></span>
                                                                                    </div>
                                                                                </div>
                                                                                <div class="databox-row row-6 padding-10">
                                                                                     <br><span><a class="btn btn-primary" style="margin-right:5px" href="<?php echo $this->baseUrl('curso/ficha?curso='.$curso['ID_CURSO_CR'])?>"><i class="fa fa-info"></i> Ficha</a><a href="<?php echo $this->baseUrl('curso/vercurso?curso='.$curso['ID_CURSO_CR'].'&slide=1')?>" class="btn btn-success" role="button"><i class="fa fa-pencil"></i>Conferir</a></span>
                                                                                </div>
                                                                            </div>
                                                                        </div>
                                                                    </div></div>
<?php $i++; }  if ($i == 1 || $i == 2 || $i == 3) { echo '</div>';} 

    } else {
        include_once APPLICATION_PATH.'/elementoshtml/alerts.php';
        Elementoshtml_Alerts::info('Voce ainda nao esta matriculado em algum curso.');
    }
?>                                                          </div>


</div>
<div id="divDados" style="display:none">
    <?php 
        include_once 'Decorators/Form.php';
        include_once 'Forms/Users.php';
        $formDec = new Decorators_Form();
        $form = new Forms_Users(array('titulo' => 'Modificar dados'));
        $form->populate($data);
        $form->addDecorator($formDec);
//        echo '<div class="row">';
        echo $form;
//        echo '</div>';
    ?>
    
</div>
<script type="text/javascript">
    $(function(){
       $('#lnkCursos').bind('click', function(){
           $('#divCursos').show();
           $('#divDados').hide();          
       });
       $('#lnkDados').bind('click', function(){
           $('#divCursos').hide();
           $('#divDados').show();
       });
       
       $('#lnkPerfil').bind('click', function() {
           $('#imgPerfil').trigger('click');
           
       });
       
       $('#imgPerfil').change(function() {
          $('#btnPerfil').trigger('click'); 
       });
    });

</script>