<html xmlns="http://www.w3.org/1999/xhtml"><!--Head-->
    <head>
    <meta charset="utf-8">
    <title>Bobby Aulas - Segurança: cadastre seu email</title>

    <meta name="description" content="login page">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon">

    <!--Basic Styles-->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link id="bootstrap-rtl-link" href="" rel="stylesheet">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">

    <!--Fonts-->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

    <!--Beyond styles-->
    <link id="beyond-link" href="assets/css/beyond.min.css" rel="stylesheet">
    <link href="assets/css/demo.min.css" rel="stylesheet">
    <link href="assets/css/animate.min.css" rel="stylesheet">
    <link id="skin-link" href="" rel="stylesheet" type="text/css">
        
    <!--Skin Script: Place this script in head to load scripts for skins and rtl support-->
    <script async="" src="http://www.google-analytics.com/analytics.js"></script><script src="assets/js/skins.min.js"></script>
</head>
<!--Head Ends-->
<!--Body-->
<body >

    
    
    <div id="esqueceu">
  <div class="login-container animated fadeInDown">
        <div class="loginbox bg-white">
            <div class="loginbox-title">CADASTRE SEU EMAIL</div>

           <form action="/aulas/public/auth/cadastroemail" method="post">
            <div class="loginbox-or">
                <div class="or-line"></div>
<!--                <div class="or">OR</div>-->
            </div>
            <input type="hidden" id="id" name="id" value="<?php 
                $request = new Zend_Controller_Request_Http();
                $params = $request->getParams();
                echo $params['faceid'];
            ?>" />
            
            <div class="loginbox-textbox">
                <input type="text" class="form-control" name="email" placeholder="Ingresse seu email...">
            </div>               
            <div class="loginbox-submit">
                <input type="submit" class="btn btn-primary btn-block" name="btnAceitar" value="Aceitar">
            </div>
            </form>
        </div>
        <div class="logobox">
        </div>
    </div>        
    </div>
    
    </div>
    <!--Basic Scripts-->
    <script src="assets/js/jquery-2.0.3.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/slimscroll/jquery.slimscroll.min.js"></script>

    <!--Beyond Scripts-->
    <script src="assets/js/beyond.js"></script>

    <!--Google Analytics::Demo Only-->
    <script>

        
        
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'http://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-52103994-1', 'auto');
        ga('send', 'pageview');

    </script>
</body></html>