<html xmlns="http://www.w3.org/1999/xhtml"><!--Head--><head>
    <meta charset="utf-8">
    <title>Login Page</title>

    <meta name="description" content="login page">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="assets/img/favicon.png" type="image/x-icon">

    <!--Basic Styles-->
    <link href="assets/css/bootstrap.min.css" rel="stylesheet">
    <link id="bootstrap-rtl-link" href="" rel="stylesheet">
    <link href="assets/css/font-awesome.min.css" rel="stylesheet">

    <!--Fonts-->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,400,600,700,300" rel="stylesheet" type="text/css">

    <!--Beyond styles-->
    <link id="beyond-link" href="assets/css/beyond.min.css" rel="stylesheet">
    <link href="assets/css/demo.min.css" rel="stylesheet">
    <link href="assets/css/animate.min.css" rel="stylesheet">
    <link id="skin-link" href="" rel="stylesheet" type="text/css">

    <!--Skin Script: Place this script in head to load scripts for skins and rtl support-->
    <script async="" src="http://www.google-analytics.com/analytics.js"></script><script src="assets/js/skins.min.js"></script>
</head>
<!--Head Ends-->
<!--Body-->
<body>
    <div id="login">
    <div class="login-container animated fadeInDown">
        <div class="loginbox bg-white">
            <div class="loginbox-title">LOG IN</div>
           <!-- <div class="loginbox-social">
                <div class="social-title ">Connect with Your Social Accounts</div>
                <div class="social-buttons">
                    <a href="" class="button-facebook">
                        <i class="social-icon fa fa-facebook"></i>
                    </a>
                    <a href="" class="button-twitter">
                        <i class="social-icon fa fa-twitter"></i>
                    </a>
                    <a href="" class="button-google">
                        <i class="social-icon fa fa-google-plus"></i>
                    </a>
                </div>
            </div>-->
           <form action="/aulas/public/auth/login" method="post">
            <div class="loginbox-or">
                <div class="or-line"></div>
<!--                <div class="or">OR</div>-->
            </div>
            <div class="loginbox-textbox">
                <input type="text" class="form-control" name="ST_USUARIO_USU" placeholder="Usuario">
            </div>
            <div class="loginbox-textbox">
                <input type="password" class="form-control" name="ST_SENHA_USU" placeholder="Senha">
            </div>
            <div class="loginbox-forgot">
                <a href="">Esqueceu a senha?</a>
            </div>
            <div class="loginbox-submit">
                <input type="submit" class="btn btn-primary btn-block" name="btnLogin" value="Logar">
            </div>
            <div class="loginbox-signup">
                <a href="javascript:void(0)" id="lnkRegister">Cadastra-se</a>
            </div>
            </form>
        </div>
        <div class="logobox">
        </div>
    </div>
    </div>
    <!--Basic Scripts-->
    <script src="assets/js/jquery-2.0.3.min.js"></script>
    <script src="assets/js/bootstrap.min.js"></script>
    <script src="assets/js/slimscroll/jquery.slimscroll.min.js"></script>

    <!--Beyond Scripts-->
    <script src="assets/js/beyond.js"></script>

    <script type="text/javascript">
    
            $(function() {
           $('#lnkRegister').bind('click',function(){
                document.getElementById('register').style.display = 'inline';
                document.getElementById('login').style.display = 'none';             
           })
           $('#lnkLogin').bind('click', function() {
                document.getElementById('login').style.display = 'inline';
                document.getElementById('register').style.display = 'none';                
           })
        });
        
    </script>
    <!--Google Analytics::Demo Only-->
    <script>

        
        
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date(); a = s.createElement(o),
            m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'http://www.google-analytics.com/analytics.js', 'ga');

        ga('create', 'UA-52103994-1', 'auto');
        ga('send', 'pageview');

    </script>
    <div id='register' style="display:none;" >
        <div class="register-container animated fadeInDown">
            <div class="registerbox bg-white">
                <div class="registerbox-title">Register</div>

                <div class="registerbox-caption ">Please fill in your information</div>
                <form method="post" action="/aulas/public/auth/signup">
                <div class="registerbox-textbox">
                    <input type="text" class="form-control" name="ST_USUARIO_USU" placeholder="Username">
                </div>
                <div class="registerbox-textbox">
                    <input type="password" class="form-control" name="ST_SENHA_USU" placeholder="Enter Password">
                </div>
                <div class="registerbox-textbox">
                    <input type="password" class="form-control" name="Confirmacao" placeholder="Confirm Password">
                </div>

                <div class="registerbox-textbox">
                    <input type="text" class="form-control" name="ST_EMAIL_USU" placeholder="E-mail">
                </div>



                <div class="registerbox-submit"><a href="javascript:void(0)" id="lnkLogin">Login</a>
                    <input type="submit" class="btn btn-primary pull-right" value="SUBMIT">
                </div>
                    </form>
            </div>
            <div class="logobox">
            </div>
        </div>

        <!--Basic Scripts-->
        <script src="assets/js/jquery-2.0.3.min.js"></script>
        <script src="assets/js/bootstrap.min.js"></script>
        <script src="assets/js/slimscroll/jquery.slimscroll.min.js"></script>

        <!--Beyond Scripts-->
        <script src="assets/js/beyond.min.js"></script>
        <!--Google Analytics::Demo Only-->
        <script>
            (function (i, s, o, g, r, a, m) {
                i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
                    (i[r].q = i[r].q || []).push(arguments)
                }, i[r].l = 1 * new Date(); a = s.createElement(o),
                m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
            })(window, document, 'script', 'http://www.google-analytics.com/analytics.js', 'ga');

            ga('create', 'UA-52103994-1', 'auto');
            ga('send', 'pageview');

        </script>
    </div>
</body></html>