<!-- MENU -->
<div class="row">
    <div class="col-md-12">
        <div class="widget">
            <div class="widget-header">
                <span class="widget-caption">
                    <a href="javascript:void(0)" id="opPencil" title="Adicionar pergunta">
                        <i class="glyphicon glyphicon-pencil"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" id="opTexto" title="Adicionar completar texto">
                        <i class="glyphicon glyphicon-file"></i>&nbsp;
                    </a> 
                </span>
            </div>
        </div>   
    </div>
</div>
<!-- FIM MENU -->

<?php

include APPLICATION_PATH.'/forms/slide/adicionar.php';
include APPLICATION_PATH.'/decorators/Form.php';


$decform = new Decorators_Form();
$form = new Forms_Slide_Adicionar(array('titulo' => 'Novo slide', 'cursos' => $this->crusos));
$form->addDecorator($decform);
echo $form;

?>
<div class="col-lg-6 col-sm-6 col-xs-12">
    <div class="widget">
        <div class="widget-header bordered-bottom bordered-blue">
            <span class="widget-caption">Elementos</span>
        </div>
        <div class="widget-body" style="display:block; overflow: hidden;">
              
            <div class="col-md-12">
                            <div class="widget flat radius-bordered">
                                <div class="widget-header bg-sky">
                                    <span class="widget-caption" id="propTitle">Propiedades</span>
                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="widget-body">
                                    <div id="propPerguntas" style="display: none;">
                                     <?php
                                        include_once APPLICATION_PATH.'/forms/exercicios/PropPerguntas.php';
                                        $formPropPerguntas = new Forms_Exercicios_PropPerguntas();
                                        echo $formPropPerguntas;
                                     ?>
                                    </div>
                                    <div id="propLinhas" style="display: none;">
                                     <?php
                                        include_once APPLICATION_PATH.'/forms/exercicios/PropLinha.php';
                                        $fromPropLinhas = new Forms_Exercicios_PropLinha();
                                        echo $fromPropLinhas;
                                     ?>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
            
            
            <div class="col-md-12">
                            <div class="widget flat radius-bordered">
                                <div class="widget-header bg-sky">
                                    <span class="widget-caption">Elementos</span>
                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="widget-body">
                                    <div id="MyTree6" class="tree tree-no-line tree-unselectable">
                                        </div>
                                </div>
                            </div>
                        </div>
            
            
        </div>
    </div>        
</div>
<div class="col-lg-6 col-sm-6 col-xs-12">
    <div class="widget">
        <div class="widget-header bordered-bottom bordered-blue">
            <span class="widget-caption">Preview</span>
        </div>
        <div class="widget-body" id="preview_visor" style="display:block; overflow: hidden;">

        </div>
    </div>        
</div>

<script type="text/javascript">
    
    function fecharTodosOsForms() {
        $('#propPerguntas').attr('style','display: none');
        $('#propLinhas').attr('style','display: none');
    }
    
    function selecionarItem() {
        fecharTodosOsForms();
        $('.itemSlide').bind('click', function() {
           fecharTodosOsForms();
            var tipo = $(this).attr('tipo');
           
            if (tipo === 'propPerguntas') {
                $('.itemSlide').parent().css('background','');
                var id = $(this).attr('id'); 
                var padre_de_this = $(this).parent();
                padre_de_this.css('background','gray');

                $('#propTitle').html('Propiedades: '+id)
                        .attr('valor',id);
                $('#propPerguntas').attr('style','display','inline');
                $('#txtId').val(id);
                window.id_pergunta = id;

                var pergunta = $('#pergunta_'+id).html();
                $('#txtPergunta').val(pergunta);
                window.pergunta = pergunta;

                var resposta = $('#respCorreta_' + id).html();
                $('#txtResposta').val(resposta);
                window.resposta = resposta;
            } 
            if (tipo === 'propLinhas') {
                $('.itemSlide').parent().css('background','');
                var id = $(this).attr('id'); 
                var padre_de_this = $(this).parent();
                padre_de_this.css('background','gray');

                $('#propTitle').html('Propiedades: '+id)
                        .attr('valor',id);
                
                $('#propLinhas').attr('style','display: block');
                
                var izq = $(this).attr('izq');
                var der = $(this).attr('der');
                var resp = $(this).attr('resp');
                var id = $(this).attr('id');
                
                $('#txtIzqLinhas').val(izq);
                $('#txtDerLinhas').val(der);
                $('#txtRespLinhas').val(resp);
                $('#txtIdLinhas').val(id);
                
                window.izq = izq;
                window.der = der;
                window.id = id;
                window.resp = resp;
                
                console.log(window.id);
            }
        });
    }
    
$(function() {
    window.perguntas = 0;
    window.tipos = [];

    $('#txtId').focusout(function() {
        var atual = $('#txtId').val();
        if (atual !== window.id_pergunta) {
            var result = $('#ST_SLIDE_SLI').html().split(window.id_pergunta).join(atual);
            $('#ST_SLIDE_SLI').html(result);
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
        }
    });
    $('#txtPergunta').focusout(function() {
        var atual = $('#txtPergunta').val();
        if (atual !== window.pergunta) {
            var result = $('#ST_SLIDE_SLI').html().split(window.pergunta).join(atual);
            $('#ST_SLIDE_SLI').html(result);
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');
        }
    });
    $('#txtResposta').focusout(function() {
        var atual = $('#txtResposta').val();
        if (atual !== window.resposta) {
            var result = $('#ST_SLIDE_SLI').html().split(window.resposta).join(atual);
            $('#ST_SLIDE_SLI').html(result);
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');
        }
    });
    
    $('#txtIdLinhas').focusout(function(){        
        var atual = $('#txtIdLinhas').val();
        if (atual !== window.id) {
            var result = $('#ST_SLIDE_SLI').html().split(window.id).join(atual);
            $('#ST_SLIDE_SLI').html(result);           
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');
        }
    });
    $('#txtRespLinhas').focusout(function(){
        var atual = $('#txtRespLinhas').val();
        if (atual !== window.resp) {
            var result = $('#ST_SLIDE_SLI').html().split(window.resp).join(atual);
            $('#ST_SLIDE_SLI').html(result);           
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');            
        }
    });
    $('#txtIzqLinhas').focusout(function(){
        var atual = $('#txtIzqLinhas').val();
        if (atual !== window.izq) {
            var result = $('#ST_SLIDE_SLI').html().split(window.izq).join(atual);
            $('#ST_SLIDE_SLI').html(result);           
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');            
        }        
    });
    $('#txtDerLinhas').focusout(function(){
        var atual = $('#txtDerLinhas').val();
        if (atual !== window.der) {
            var result = $('#ST_SLIDE_SLI').html().split(window.der).join(atual);
            $('#ST_SLIDE_SLI').html(result);           
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');            
        }         
    });
    

    $('#Preview').bind('click', function() {
        var html = $('#ST_SLIDE_SLI').val();
        $('#preview_visor').html(html);
    });
    
    $('#opTexto').bind('click', function() {
       window.perguntas += 1;
       var n = window.perguntas;
       agregarHtmlText();
       agregarElemento('propLinhas', 'id="pergunta'+n+'" izq="izq'+n+'" der="der'+n+'" resp="resp'+n+'" ');
        $('#Preview').trigger('click');
        
    });
    
    $('#opPencil').bind('click', function() {
        
        window.perguntas += 1;
        var n = window.perguntas;
        agregarHtmlPerguntas();
        agregarElemento('propPerguntas','id="pergunta'+n+'" pergunta="pergunta'+n+'" resposta="resposta'+n+'"');
        $('#Preview').trigger('click');
    });
});
    
function adicionarNaEstrutura(tag, id, campos) { 
    var item =  '<div class="tree-item" style="display: block;">\n\
                    <i class="tree-dot"></i>\n\
                    <div class="tree-item-name itemSlide" '+campos+' tipo="'+window.tipos[window.contador]+'" id='+id+'>\n\
                        <i class="fa fa-suitcase"></i> \n\
                        '+ tag +'[ ' + id + ' ] \n\
                        <div class="tree-actions">\n\
                            <i class="fa fa-plus"></i>\n\
                            <i class="fa fa-trash-o"></i>\n\
                            <i class="fa fa-refresh"></i>\n\
                        </div>\n\
                    </div>\n\
                 </div>';
                                
    $('#MyTree6').append(item);
    window.contador++;
    selecionarItem();
}

function agregarElemento(tipo, campos, id) {
    var item =  '<div class="tree-item" style="display: block;">\n\
                    <i class="tree-dot"></i>\n\
                    <div class="tree-item-name itemSlide" '+campos+' tipo="'+tipo+'">\n\
                        <i class="fa fa-suitcase"></i> \n\
                        '+id+' \n\
                        <div class="tree-actions">\n\
                            <i class="fa fa-plus"></i>\n\
                            <i class="fa fa-trash-o"></i>\n\
                            <i class="fa fa-refresh"></i>\n\
                        </div>\n\
                    </div>\n\
                 </div>';
                                
    $('#MyTree6').append(item);
    selecionarItem();    
}
function agregarHtmlText() {
           var pergunta = '<div id="horizontal-form">\n\
                                                <form class="form-horizontal" role="form"><div class="row">\n\
                                                    <div class="form-group">\n\
                                                        <label id="pergunta1_izquerda" for="A" class="col-sm-2 control-label no-padding-right">izq'+window.perguntas+'</label>\n\
                                                        <div class="col-sm-2 " style="padding-left:2px; padding-right:2px">\n\
                                                        <span class="input-icon icon-right">\n\
                                                            <input type="text" class="form-control" id="pergunta'+window.perguntas+'" name="pergunta'+window.perguntas+'" placeholder=""/>\n\
                                                            <i class="fa fa-times red" id="pergunta'+window.perguntas+'_times" style=""></i>\n\
                                                            <i class="fa fa-check green" id="pergunta'+window.perguntas+'_check" style="display:none"></i></span>\n\
                                                        </div>\n\
<div class="col-sm-2" style="padding-left:0px;padding-right:0px;">\n\
                                                           <label id="pergunta'+window.perguntas+'_direita" for="A" class="control-label no-padding-right">der'+window.perguntas+'</label>\n\
                                                        </div>\n\
                                                    </div></div></form></div>'; 
                    var atualHtml = $('#ST_SLIDE_SLI').html();
        atualHtml += pergunta;
        $('#ST_SLIDE_SLI').html(atualHtml);                                                    
                                                                
    }
function agregarHtmlPerguntas() {
 var pergunta = '<div class="form-group col-sm-12">\n\
                <div class="row">\n\
                    <div class="col-sm-9"> \n\
                        <label for="pergunta" id="pergunta_pergunta'+window.perguntas+'">[Pergunta]</label> \n\
                    </div>\n\
                        <div class="col-sm-3"> \n\
                            <span id="respCorreta_pergunta'+window.perguntas+'" class="text-align-right green">[Resposta]</span>\n\
                        </div>\n\
                    </div>\n\
                        <span class="input-icon icon-right"> \n\
                            <input type="text" class="form-control" name="pergunta'+window.perguntas+'" id="pergunta'+window.perguntas+'" placeholder="Resposta">\n\
                            <i class="fa fa-times" id="pergunta'+window.perguntas+'_times" style="display:none"></i>\n\
                            <i class="fa fa-check" id="pergunta'+window.perguntas+'_check" style="display:none"></i>\n\
                        </span>\n\
                    </div>';
        var atualHtml = $('#ST_SLIDE_SLI').html();
        atualHtml += pergunta;
        $('#ST_SLIDE_SLI').html(atualHtml);   
}
</script>