<!-- MENU -->
<div class="row">
    <div class="col-md-12">
        <div class="widget">
            <div class="widget-header">
                <span class="widget-caption">
                    <a href="javascript:void(0)" id="opPencil" title="Adicionar pergunta">
                        <i class="glyphicon glyphicon-pencil"></i>&nbsp;
                    </a>
                    <a href="javascript:void(0)" id="opTexto" title="Adicionar completar texto">
                        <i class="glyphicon glyphicon-file"></i>&nbsp;
                    </a> 
                </span>
            </div>
        </div>   
    </div>
</div>
<!-- FIM MENU -->

<?php

include APPLICATION_PATH.'/forms/slide/adicionar.php';
include APPLICATION_PATH.'/decorators/Form.php';


$decform = new Decorators_Form();
$form = new Forms_Slide_Adicionar(array('titulo' => 'Novo slide', 'cursos' => $this->crusos));
$form->addDecorator($decform);
echo $form;

?>
<div class="col-lg-6 col-sm-6 col-xs-12">
    <div class="widget">
        <div class="widget-header bordered-bottom bordered-blue">
            <span class="widget-caption">Elementos</span>
        </div>
        <div class="widget-body" style="display:block; overflow: hidden;">
              
            <div class="col-md-12">
                            <div class="widget flat radius-bordered">
                                <div class="widget-header bg-sky">
                                    <span class="widget-caption" id="propTitle">Propiedades</span>
                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="widget-body">
                                    <div id="propPerguntas" style="display: none;">
                                     <?php
                                        include_once APPLICATION_PATH.'/forms/exercicios/PropPerguntas.php';
                                        $formPropPerguntas = new Forms_Exercicios_PropPerguntas();
                                        echo $formPropPerguntas;
                                     ?>
                                    </div>
                                    <div id="propLinhas" style="display: none;">
                                     <?php
                                        include_once APPLICATION_PATH.'/forms/exercicios/PropLinha.php';
                                        $fromPropLinhas = new Forms_Exercicios_PropLinha();
                                        echo $fromPropLinhas;
                                     ?>
                                    </div>                                    
                                </div>
                            </div>
                        </div>
            
            
            <div class="col-md-12">
                            <div class="widget flat radius-bordered">
                                <div class="widget-header bg-sky">
                                    <span class="widget-caption">Elementos</span>
                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="widget-body">
                                    <div id="MyTree6" class="tree tree-no-line tree-unselectable">
                                        </div>
                                </div>
                            </div>
                        </div>
            
            
        </div>
    </div>        
</div>
<div class="col-lg-6 col-sm-6 col-xs-12">
    <div class="widget">
        <div class="widget-header bordered-bottom bordered-blue">
            <span class="widget-caption">Preview</span>
        </div>
        <div class="widget-body" id="preview_visor" style="display:block; overflow: hidden;">

        </div>
    </div>        
</div>

<script type="text/javascript">
    
    function fecharTodosOsForms() {
        $('#propPerguntas').attr('style','display: none');
        $('#propLinhas').attr('style','display: none');
    }
    
    function selecionarItem() {
        fecharTodosOsForms();
        $('.itemSlide').bind('click', function() {
           fecharTodosOsForms();
            var tipo = $(this).attr('tipo');
           
            if (tipo === 'propPerguntas') {
                $('.itemSlide').parent().css('background','');
                var id = $(this).attr('id'); 
                var padre_de_this = $(this).parent();
                padre_de_this.css('background','gray');

                $('#propTitle').html('Propiedades: '+id)
                        .attr('valor',id);
                $('#propPerguntas').attr('style','display','inline');
                $('#txtId').val(id);
                window.id_pergunta = id;

                var pergunta = $('#pergunta_'+id).html();
                $('#txtPergunta').val(pergunta);
                window.pergunta = pergunta;

                var resposta = $('#respCorreta_' + id).html();
                $('#txtResposta').val(resposta);
                window.resposta = resposta;
            } 
            if (tipo === 'propLinhas') {
                 $('.itemSlide').parent().css('background','');
                var id = $(this).attr('id'); 
                var padre_de_this = $(this).parent();
                padre_de_this.css('background','gray');

                $('#propTitle').html('Propiedades: '+id)
                        .attr('valor',id);
                
                $('#propLinhas').attr('style','display: block');
            }
        });
    }
    
$(function() {
    window.perguntas = 1;
    window.tipos = [];

//    $('#MyTree6').append('<div class="tree-item" style="display: block;">\n\
//                    <i class="tree-dot"></i>\n\
//                    <div class="tree-item-name itemSlide" tipo="propPerguntas" id="pergunta2">\n\
//                        <i class="fa fa-suitcase"></i>input[ pergunta2 ]<div class="tree-actions">\n\
//                            <i class="fa fa-plus"></i>\n\
//                            <i class="fa fa-trash-o"></i>\n\
//                            <i class="fa fa-refresh"></i>\n\
//                        </div>\n\
//                    </div>\n\
//                 </div>');

    $('#txtId').focusout(function() {
        var atual = $('#txtId').val();
        if (atual !== window.id_pergunta) {
            var result = $('#ST_SLIDE_SLI').html().split(window.id_pergunta).join(atual);
            $('#ST_SLIDE_SLI').html(result);
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
        }
    });

    $('#txtPergunta').focusout(function() {
        var atual = $('#txtPergunta').val();
        if (atual !== window.pergunta) {
            var result = $('#ST_SLIDE_SLI').html().split(window.pergunta).join(atual);
            $('#ST_SLIDE_SLI').html(result);
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');
        }
    });

    $('#txtResposta').focusout(function() {
        var atual = $('#txtResposta').val();
        if (atual !== window.resposta) {
            var result = $('#ST_SLIDE_SLI').html().split(window.resposta).join(atual);
            $('#ST_SLIDE_SLI').html(result);
            Notify('Alteração correta!', 'top-right', '5000', 'success', 'fa-check', false);
            $('#Preview').trigger('click');
        }
    });
    

    $('#Preview').bind('click', function() {
        var html = $('#ST_SLIDE_SLI').val();
        $('#preview_visor').html(html);
    });
    
    $('#opTexto').bind('click', function() {
        
        //Tengo el codigo
        //Agrego en el arbol
            // para esto tengo que tener valores de secuencia ya
        
        window.contador = 0;
       var pergunta = '<div id="horizontal-form">\n\
                                                <form class="form-horizontal" role="form"><div class="row">\n\
                                                    <div class="form-group">\n\
                                                        <label id="pergunta1_izquerda" for="A" class="col-sm-2 control-label no-padding-right">A </label>\n\
                                                        <div class="col-sm-2 " style="padding-left:2px; padding-right:2px">\n\
                                                        <span class="input-icon icon-right">\n\
                                                            <input type="text" class="form-control" id="pergunta'+window.perguntas+'" name="pergunta'+window.perguntas+'" placeholder=""/>\n\
                                                            <i class="fa fa-times red" id="pergunta'+window.perguntas+'_times" style=""></i>\n\
                                                            <i class="fa fa-check green" id="pergunta'+window.perguntas+'_check" style="display:none"></i></span>\n\
                                                        </div>\n\
<div class="col-sm-2" style="padding-left:0px;padding-right:0px;">\n\
                                                           <label id="pergunta'+window.perguntas+'_direita" for="A" class="control-label no-padding-right">A - </label>\n\
                                                        </div>\n\
                                                    </div></div></form></div>'; 
       
        var atualHtml = $('#ST_SLIDE_SLI').html();
        atualHtml += pergunta;
        $('#ST_SLIDE_SLI').html(atualHtml);
        
        $('#MyTree6').html('');
        $('#Preview').trigger('click');
        window.tipos.push('propLinhas'); 
        arvore($('#ST_SLIDE_SLI'));
        window.perguntas += 1;
          
        console.log(window.tipos);
    });
    
    $('#opPencil').bind('click', function() {
        
        window.perguntas += 1;
        var n = window.perguntas;
        agregarHtmlPerguntas();
        agregarElemento('propPerguntas','id="pergunta'+n+'" pergunta="pergunta'+n+'" resposta="resposta'+n+'"');
        $('#Preview').trigger('click');
    });
});


function arvore(selector) {
   
    var cadena = selector.text();
    
    for (var i = 0; i < cadena.length; i++) {
        if (cadena[i] === '<') {
            buscarTag(cadena, i);
        }
    }
}

function inputId(cadena, i) {
    var ok = false;
    var id = '';
    while(!ok) {
        if (cadena[i] === 'i' && cadena[i + 1] === 'd') {
            //cadena i+2 = '='
            //cadena i+3 = '"'
            i = i + 4;
            while (cadena[i] !== '"') {
                id += cadena[i];
                i++;
            }
            ok = true;
        }
        i++;
    }    
    return id;
}

function buscarTag(cadena, i) {
    i++;
    var tag = '';
    var ok = true;
    while (ok) {      
        tag += cadena[i];
        i++;
        if (cadena[i] === ' ' || cadena[i] === '>') {
            ok = false;
        }          
    }
    
    if (tag.search('/') !== 0) {
        //console.log(tag);    
    }
    if (tag === 'input') {
        
        var id = inputId(cadena, i);
        adicionarNaEstrutura(tag, id, null);
    }
    return tag;
}

function valoresInput(cadena, i) {
    var arrayValores = [];
    var input = '';
    while (cadena[i] !== '>') {
        input += cadena[i];
        i++;
    }
}
    
function adicionarNaEstrutura(tag, id, campos) { 
    var item =  '<div class="tree-item" style="display: block;">\n\
                    <i class="tree-dot"></i>\n\
                    <div class="tree-item-name itemSlide" '+campos+' tipo="'+window.tipos[window.contador]+'" id='+id+'>\n\
                        <i class="fa fa-suitcase"></i> \n\
                        '+ tag +'[ ' + id + ' ] \n\
                        <div class="tree-actions">\n\
                            <i class="fa fa-plus"></i>\n\
                            <i class="fa fa-trash-o"></i>\n\
                            <i class="fa fa-refresh"></i>\n\
                        </div>\n\
                    </div>\n\
                 </div>';
                                
    $('#MyTree6').append(item);
    window.contador++;
    selecionarItem();
}

function agregarElemento(tipo, campos, id) {
//    var item =  '<div class="tree-item" style="display: block;">\n\
//                    <i class="tree-dot"></i>\n\
//                    <div class="tree-item-name itemSlide" '+campos+' tipo="'+tipos+'">\n\
//                        <i class="fa fa-suitcase"></i> \n\
//                        '[ ' + id + ' ] \n\
//                        <div class="tree-actions">\n\
//                            <i class="fa fa-plus"></i>\n\
//                            <i class="fa fa-trash-o"></i>\n\
//                            <i class="fa fa-refresh"></i>\n\
//                        </div>\n\
//                    </div>\n\
//                 </div>';
//                                
//    $('#MyTree6').append(item);
//    window.contador++;
//    selecionarItem();    
}

function agregarHtmlPerguntas() {
 var pergunta = '<div class="form-group col-sm-12">\n\
                <div class="row">\n\
                    <div class="col-sm-9"> \n\
                        <label for="pergunta" id="pergunta_pergunta'+window.perguntas+'">[Pergunta]</label> \n\
                    </div>\n\
                        <div class="col-sm-3"> \n\
                            <span id="respCorreta_pergunta'+window.perguntas+'" class="text-align-right green">[Resposta]</span>\n\
                        </div>\n\
                    </div>\n\
                        <span class="input-icon icon-right"> \n\
                            <input type="text" class="form-control" name="pergunta'+window.perguntas+'" id="pergunta'+window.perguntas+'" placeholder="Resposta">\n\
                            <i class="fa fa-times" id="pergunta'+window.perguntas+'_times" style="display:none"></i>\n\
                            <i class="fa fa-check" id="pergunta'+window.perguntas+'_check" style="display:none"></i>\n\
                        </span>\n\
                    </div>';
        var atualHtml = $('#ST_SLIDE_SLI').html();
        atualHtml += pergunta;
        $('#ST_SLIDE_SLI').html(atualHtml);   
}
</script>