<?php

$usuarios = $this->pendentes;

?>
 <div class="row">
                        <div class="col-xs-12 col-md-12">
                            <div class="widget">
                                <div class="widget-header bordered-bottom bordered-yellow">
                                    <span class="widget-caption">Usuários</span>
                                    <div class="widget-buttons">
                                        <a href="#" data-toggle="maximize">
                                            <i class="fa fa-expand"></i>
                                        </a>
                                        <a href="#" data-toggle="collapse">
                                            <i class="fa fa-minus"></i>
                                        </a>
                                        <a href="#" data-toggle="dispose">
                                            <i class="fa fa-times"></i>
                                        </a>
                                    </div>
                                </div>
                                <div class="widget-body">
                                    <div class="table-toolbar">
             
                                        </div>
                                    </div>
                                    <table class="table table-bordered table-hover table-striped dataTable" id="editabledatatable">
                                        <thead>
                                            <tr role="row">
                                                <th>
                                                    ID
                                                </th>
                                                <th>
                                                    Usuário
                                                </th>
                                                <th>
                                                    E-mail
                                                </th>
                                                 <th>
                                                    Data crédito
                                                </th>
                                                 <th>
                                                    Crédito $
                                                </th>
                                                <th>
                                                    Pendente
                                                </th>
                                                 <th>
                                                    Opcões
                                                </th>
                                            </tr>
                                        </thead>

                                        <tbody>
                                            
                                            <?php 
                                            foreach ($usuarios as $usuario):
                                                $active['pago'] = $usuario['FL_PENDENTE'] > 0 ? 'active' : '';
                                                $active['naoPago'] = $usuario['FL_PENDENTE'] < 1 ? 'active' : '';
                                            ?>
                                            <tr>
                                                <td><?php echo $usuario['ID_ID_USU']?></td>
                                                <td><?php echo $usuario['ST_USUARIO_USU']?></td>
                                                <td class="center "><?php echo $usuario['ST_EMAIL_USU']?></td>
                                                <td><?php echo date('d/m/Y H:i:s',  strtotime($usuario['DT_DATA_CREDITO_PEN']));?></td>
                                                <td><i class="fa fa-dollar">&nbsp;</i><?php echo $usuario['VL_VALOR_CREDITO_PEN']?></td>
                                                <td>
                                                    <div class="" data-toggle="buttons">
                                                        <label class="btn btn-xs btn-success <?php echo $active['pago']; ?>">
                                                            <i class="fa fa-check"></i> Pago
                                                        </label>
                                                        <label class="btn btn-xs btn-danger <?php echo $active['naoPago']; ?>">
                                                            <input type="radio" name="pendente" id="option2" autocomplete="off" data-id="<?php echo $usuario['ID_CREDITO_PEN']?>" data-pendente="<?php echo $usuario['FL_PENDENTE']?>" onchange="alterarPendentes(this)">
                                                            <i class="fa fa-warning"></i> Não pago
                                                        </label>          
                                                    </div> 
                                                </td>
                                                <td>                                    
                                                    <a href="#" id="excluir"onclick="confirmDialog(this,'<?php echo $usuario['ST_USUARIO_USU']?>')" class="btn btn-danger btn-xs delete" <?php echo $usuario['FL_PENDENTE'] == 0 ? 'disabled':'' ?>><i class="fa fa-trash-o"></i> Excluir</a>
                                                </td>
                                            </tr>
                                            <?php endforeach;?>
                                        </tbody>
                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>


