
<?php 
include APPLICATION_PATH.'/Forms/Credito.php';

$storage = new Zend_Auth_Storage_Session();
$data = (get_object_vars($storage->read()));
$usuario = $data['ST_USUARIO_USU'];
$id = (int)$data['ID_ID_USU'];
?>

<!-- Adicionar credito-->
<div class="row">
    <div class="col-lg-8 col-sm-8 col-xs-12">
        <div class="widget">

                    <?php
                       $form = new Forms_Credito();
                       $form->addElement('hidden',
                               'ID',
                                array('value'=>$id));
                    echo $form;
                    
                    ?>
        </div>
    </div>
    <!-- Historico de credito-->
        <div class="col-lg-4 col-sm-4 col-xs-12">
        <div class="widget">
            <div class="widget-header bordered-bottom bg-blue">
                <span class="widget-caption"><span class="databox-title"> Historico de crédito </span>  </span>
            </div>
                <div class="widget-body bg-blue">
                    
                </div>
        </div>
    </div>
</div>